// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.ledger.model



/**
 * Ledger assignments to ledger group
 */
data class LedgerGroupLedgerId(

    /**
     * Ledger Group Id
     */
    var ledgerGroupId: String = "",

    /**
     * Ledger Id
     */
    var ledgerId: String = "",
) : Serializable 