// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.ca.uom.model



/**
 * Unit of measurement text
 */
data class UnitOfMeasurementTextId(

    /**
     * Language Id
     */
    var languageId: String = "",

    /**
     * Unit of measurement Id
     */
    var uomId: String = "",
) : Serializable 