// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-18 21:59:59

package finance.data.ca.uom.model



/**
 * Unit of measurement text
 */
data class UnitOfMeasurementTextId(

    /**
     * Language Id
     */
    var languageId: String = "",

    /**
     * Unit of measurement Id
     */
    var uomId: String = "",
) : Serializable 