// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.ledger_entry.model

import jakarta.persistence.*
import java.util.UUID
import finance.data.analytics.model.AttributeValueEntity


/**
 * Ledger entry attribute
 */
@Entity
@Table(name = "ledger_entry_attributes", schema = "ledger_entry")
@IdClass(LedgerEntryAttributeId::class)
data class LedgerEntryAttributeEntity(

    /**
     * Entry no
     */
    @Id
    @Column(name = "entry_no", nullable = false)
    var entryNo: UUID,

    /**
     * Attribute id
     */
    @Id
    @Column(name = "attribute_id", nullable = false, length = 10)
    var attributeId: String,

    /**
     * Attribute value id
     */
    @Id
    @Column(name = "attribute_value_id", nullable = false, length = 20)
    var attributeValueId: String,

    /**
     * Reference to LedgerEntry
     */
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "entry_no", referencedColumnName = "entry_no", nullable = false, updatable = false, insertable = false)
    var ledgerEntry: LedgerEntryEntity? = null,

    /**
     * Reference to AttributeValue
     */
    @JsonIgnore
    @ManyToOne
    @JoinColumn([
      @JoinColumn(name = "attribute_id", referencedColumnName = "attribute_id", nullable = false, updatable = false, insertable = false),
      @JoinColumn(name = "attribute_value_id", referencedColumnName = "attribute_value_id", nullable = false, updatable = false, insertable = false),
    ])
    var attributeValue: AttributeValueEntity? = null,
) 