// Order Status
enum order_status {
  P [note: 'Placed']
  D [note: 'Delivered']
  C [note: 'Canceled']
}


// Group Client - Client tables 

table client.clients {
  id integer [pk, not null, increment, note: 'Client Id']
  name varchar(100) [not null, note: 'Client name']
  description text [note: 'Description']
  billing_address_line1 varchar(100) [not null, note: 'First address line']
  billing_address_line2 varchar(100) [note: 'Second address line']
  billing_city varchar(50) [not null, note: 'City']
  billing_state varchar(50) [not null, note: 'State']
  billing_country varchar(50) [not null, note: 'Country']
  billing_postcode varchar(10) [not null, note: 'Post code']
  postal_address_line1 varchar(100) [not null, note: 'First address line']
  postal_address_line2 varchar(100) [note: 'Second address line']
  postal_city varchar(50) [not null, note: 'City']
  postal_state varchar(50) [not null, note: 'State']
  postal_country varchar(50) [not null, note: 'Country']
  postal_postcode varchar(10) [not null, note: 'Post code']
  promotion_id varchar(10) [note: 'Promotion Id']
  segment_id varchar(10) [note: 'Segment Id']
  business_area_id varchar(10) [note: 'Business Area Id']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  note: 'Client'
}

// Reference to Promotion
Ref clients_promotion_id: client.clients.promotion_id > analytics.promotions.id
// Reference to Segment
Ref clients_segment_id: client.clients.segment_id > analytics.segments.id
// Reference to BusinessArea
Ref clients_business_area_id: client.clients.business_area_id > analytics.business_areas.id


table client.client_addresses {
  id integer [pk, not null, increment, note: 'Address Id']
  name varchar(100) [not null, note: 'Address name']
  description text [note: 'Description']
  client_id integer [not null, note: 'Client Id']
  address_line1 varchar(100) [not null, note: 'First address line']
  address_line2 varchar(100) [note: 'Second address line']
  city varchar(50) [not null, note: 'City']
  state varchar(50) [not null, note: 'State']
  country varchar(50) [not null, note: 'Country']
  postcode varchar(10) [not null, note: 'Post code']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    (client_id, id) [unique, name: 'client_addresses_client_id_id', note: 'Unique clientId & id']
  }

  note: 'Client address'
}

// Reference to client
Ref client_addresses_client_id: client.client_addresses.client_id > client.clients.id



// Group Order - Order tables 

table orders {
  id integer [pk, not null, increment, note: 'Order Id']
  name varchar(100) [not null, note: 'Order name']
  description text [note: 'Description']
  client_id integer [not null, note: 'Client Id']
  delivery_address_id integer [not null, note: 'Delivery address']
  status order_status [not null, note: 'Order status']
  promotion_id varchar(10) [note: 'Promotion Id']
  segment_id varchar(10) [note: 'Segment Id']
  business_area_id varchar(10) [note: 'Business Area Id']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  note: 'Order'
}

// Reference to client
Ref orders_client_id: orders.client_id > client.clients.id
// Reference to address
Ref orders_delivery_address_id: orders.(client_id, delivery_address_id) > client.client_addresses.(client_id, id)
// Reference to Promotion
Ref orders_promotion_id: orders.promotion_id > analytics.promotions.id
// Reference to Segment
Ref orders_segment_id: orders.segment_id > analytics.segments.id
// Reference to BusinessArea
Ref orders_business_area_id: orders.business_area_id > analytics.business_areas.id


table order_lines {
  id integer [pk, not null, increment, note: 'OrderLine Id']
  order_id integer [not null, note: 'Order Id']
  item_id integer [not null, note: 'Item Id']
  promotion_id varchar(10) [note: 'Promotion Id']
  segment_id varchar(10) [note: 'Segment Id']
  business_area_id varchar(10) [note: 'Business Area Id']
  price decimal(10,2) [not null, note: 'Amount']
  quantity decimal(10,2) [not null, note: 'Quantity']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  note: 'Order line'
}

// Reference to order
Ref order_lines_order_id: order_lines.order_id > orders.id
// Reference to item
Ref order_lines_item_id: order_lines.item_id > items.id
// Reference to Promotion
Ref order_lines_promotion_id: order_lines.promotion_id > analytics.promotions.id
// Reference to Segment
Ref order_lines_segment_id: order_lines.segment_id > analytics.segments.id
// Reference to BusinessArea
Ref order_lines_business_area_id: order_lines.business_area_id > analytics.business_areas.id


table items {
  id integer [pk, not null, increment, note: 'Item Id']
  item_id integer [not null, note: 'Item Id']
  price decimal(10,2) [not null, note: 'Amount']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  note: 'Item'
}


// Group Analytics - Analytic tables 

table analytics.segments {
  id varchar(10) [pk, not null, note: 'Segment Id']
  name varchar(100) [not null, note: 'Name']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  note: 'Segment'
}

table analytics.business_areas {
  id varchar(10) [pk, not null, note: 'Business Area Id']
  name varchar(100) [not null, note: 'Name']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  note: 'Business area'
}

table analytics.promotions {
  id varchar(10) [pk, not null, note: 'Promotion Id']
  name varchar(100) [not null, note: 'Name']
  created_by varchar(10) [not null, note: 'User created record']
  created_at timestamptz [not null, note: 'Timestamp of record create']
  updated_by varchar(10) [not null, note: 'User updated record']
  updated_at timestamptz [not null, note: 'Timestamp of record update']

  note: 'Promotion'
}

