-- Store example
-- Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).


CREATE TABLE "client"."client_clients" (
  "id" serial PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "billing_address_line1" varchar(100) NOT NULL,
  "billing_address_line2" varchar(100),
  "billing_city" varchar(50) NOT NULL,
  "billing_state" varchar(50) NOT NULL,
  "billing_country" varchar(50) NOT NULL,
  "billing_postcode" varchar(10) NOT NULL,
  "postal_address_line1" varchar(100) NOT NULL,
  "postal_address_line2" varchar(100),
  "postal_city" varchar(50) NOT NULL,
  "postal_state" varchar(50) NOT NULL,
  "postal_country" varchar(50) NOT NULL,
  "postal_postcode" varchar(10) NOT NULL,
  "promotion_id" varchar(10),
  "segment_id" varchar(10),
  "business_area_id" varchar(10),
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "client"."client_client_addresses" (
  "id" serial PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "client_id" integer NOT NULL,
  "address_line1" varchar(100) NOT NULL,
  "address_line2" varchar(100),
  "city" varchar(50) NOT NULL,
  "state" varchar(50) NOT NULL,
  "country" varchar(50) NOT NULL,
  "postcode" varchar(10) NOT NULL,
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "order_orders" (
  "id" serial PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "client_id" integer NOT NULL,
  "delivery_address_id" integer NOT NULL,
  "status" order_status NOT NULL,
  "promotion_id" varchar(10),
  "segment_id" varchar(10),
  "business_area_id" varchar(10),
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "order_order_lines" (
  "id" serial PRIMARY KEY NOT NULL,
  "order_id" integer NOT NULL,
  "item_id" integer NOT NULL,
  "promotion_id" varchar(10),
  "segment_id" varchar(10),
  "business_area_id" varchar(10),
  "price" decimal(10,2) NOT NULL,
  "quantity" decimal(10,2) NOT NULL,
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "order_items" (
  "id" serial PRIMARY KEY NOT NULL,
  "item_id" integer NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."analytics_segments" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."analytics_business_areas" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."analytics_promotions" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(10) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(10) NOT NULL,
  "updated_at" timestamptz NOT NULL
);


CREATE UNIQUE INDEX "client_client_addresses_client_id_id" ON "client"."client_client_addresses" ("client_id", "id");


COMMENT ON TABLE "client"."client_clients" IS 'Client';

COMMENT ON COLUMN "client"."client_clients"."id" IS 'Client Id';

COMMENT ON COLUMN "client"."client_clients"."name" IS 'Client name';

COMMENT ON COLUMN "client"."client_clients"."description" IS 'Description';

COMMENT ON COLUMN "client"."client_clients"."billing_address_line1" IS 'First address line';

COMMENT ON COLUMN "client"."client_clients"."billing_address_line2" IS 'Second address line';

COMMENT ON COLUMN "client"."client_clients"."billing_city" IS 'City';

COMMENT ON COLUMN "client"."client_clients"."billing_state" IS 'State';

COMMENT ON COLUMN "client"."client_clients"."billing_country" IS 'Country';

COMMENT ON COLUMN "client"."client_clients"."billing_postcode" IS 'Post code';

COMMENT ON COLUMN "client"."client_clients"."postal_address_line1" IS 'First address line';

COMMENT ON COLUMN "client"."client_clients"."postal_address_line2" IS 'Second address line';

COMMENT ON COLUMN "client"."client_clients"."postal_city" IS 'City';

COMMENT ON COLUMN "client"."client_clients"."postal_state" IS 'State';

COMMENT ON COLUMN "client"."client_clients"."postal_country" IS 'Country';

COMMENT ON COLUMN "client"."client_clients"."postal_postcode" IS 'Post code';

COMMENT ON COLUMN "client"."client_clients"."promotion_id" IS 'Promotion Id';

COMMENT ON COLUMN "client"."client_clients"."segment_id" IS 'Segment Id';

COMMENT ON COLUMN "client"."client_clients"."business_area_id" IS 'Business Area Id';

COMMENT ON COLUMN "client"."client_clients"."created_by" IS 'User created record';

COMMENT ON COLUMN "client"."client_clients"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "client"."client_clients"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "client"."client_clients"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "client"."client_client_addresses" IS 'Client address';

COMMENT ON COLUMN "client"."client_client_addresses"."id" IS 'Address Id';

COMMENT ON COLUMN "client"."client_client_addresses"."name" IS 'Address name';

COMMENT ON COLUMN "client"."client_client_addresses"."description" IS 'Description';

COMMENT ON COLUMN "client"."client_client_addresses"."client_id" IS 'Client Id';

COMMENT ON COLUMN "client"."client_client_addresses"."address_line1" IS 'First address line';

COMMENT ON COLUMN "client"."client_client_addresses"."address_line2" IS 'Second address line';

COMMENT ON COLUMN "client"."client_client_addresses"."city" IS 'City';

COMMENT ON COLUMN "client"."client_client_addresses"."state" IS 'State';

COMMENT ON COLUMN "client"."client_client_addresses"."country" IS 'Country';

COMMENT ON COLUMN "client"."client_client_addresses"."postcode" IS 'Post code';

COMMENT ON COLUMN "client"."client_client_addresses"."created_by" IS 'User created record';

COMMENT ON COLUMN "client"."client_client_addresses"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "client"."client_client_addresses"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "client"."client_client_addresses"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "order_orders" IS 'Order';

COMMENT ON COLUMN "order_orders"."id" IS 'Order Id';

COMMENT ON COLUMN "order_orders"."name" IS 'Order name';

COMMENT ON COLUMN "order_orders"."description" IS 'Description';

COMMENT ON COLUMN "order_orders"."client_id" IS 'Client Id';

COMMENT ON COLUMN "order_orders"."delivery_address_id" IS 'Delivery address';

COMMENT ON COLUMN "order_orders"."status" IS 'Order status';

COMMENT ON COLUMN "order_orders"."promotion_id" IS 'Promotion Id';

COMMENT ON COLUMN "order_orders"."segment_id" IS 'Segment Id';

COMMENT ON COLUMN "order_orders"."business_area_id" IS 'Business Area Id';

COMMENT ON COLUMN "order_orders"."created_by" IS 'User created record';

COMMENT ON COLUMN "order_orders"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "order_orders"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "order_orders"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "order_order_lines" IS 'Order line';

COMMENT ON COLUMN "order_order_lines"."id" IS 'OrderLine Id';

COMMENT ON COLUMN "order_order_lines"."order_id" IS 'Order Id';

COMMENT ON COLUMN "order_order_lines"."item_id" IS 'Item Id';

COMMENT ON COLUMN "order_order_lines"."promotion_id" IS 'Promotion Id';

COMMENT ON COLUMN "order_order_lines"."segment_id" IS 'Segment Id';

COMMENT ON COLUMN "order_order_lines"."business_area_id" IS 'Business Area Id';

COMMENT ON COLUMN "order_order_lines"."price" IS 'Amount';

COMMENT ON COLUMN "order_order_lines"."quantity" IS 'Quantity';

COMMENT ON COLUMN "order_order_lines"."created_by" IS 'User created record';

COMMENT ON COLUMN "order_order_lines"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "order_order_lines"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "order_order_lines"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "order_items" IS 'Item';

COMMENT ON COLUMN "order_items"."id" IS 'Item Id';

COMMENT ON COLUMN "order_items"."item_id" IS 'Item Id';

COMMENT ON COLUMN "order_items"."price" IS 'Amount';

COMMENT ON COLUMN "order_items"."created_by" IS 'User created record';

COMMENT ON COLUMN "order_items"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "order_items"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "order_items"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."analytics_segments" IS 'Segment';

COMMENT ON COLUMN "analytics"."analytics_segments"."id" IS 'Segment Id';

COMMENT ON COLUMN "analytics"."analytics_segments"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."analytics_segments"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."analytics_segments"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."analytics_segments"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."analytics_segments"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."analytics_business_areas" IS 'Business area';

COMMENT ON COLUMN "analytics"."analytics_business_areas"."id" IS 'Business Area Id';

COMMENT ON COLUMN "analytics"."analytics_business_areas"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."analytics_business_areas"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."analytics_business_areas"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."analytics_business_areas"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."analytics_business_areas"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."analytics_promotions" IS 'Promotion';

COMMENT ON COLUMN "analytics"."analytics_promotions"."id" IS 'Promotion Id';

COMMENT ON COLUMN "analytics"."analytics_promotions"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."analytics_promotions"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."analytics_promotions"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."analytics_promotions"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."analytics_promotions"."updated_at" IS 'Timestamp of record update';



ALTER TABLE "client"."client_clients" ADD CONSTRAINT "client_clients_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "analytics"."analytics_promotions" ("id");

ALTER TABLE "client"."client_clients" ADD CONSTRAINT "client_clients_segment_id" FOREIGN KEY ("segment_id") REFERENCES "analytics"."analytics_segments" ("id");

ALTER TABLE "client"."client_clients" ADD CONSTRAINT "client_clients_business_area_id" FOREIGN KEY ("business_area_id") REFERENCES "analytics"."analytics_business_areas" ("id");

ALTER TABLE "client"."client_client_addresses" ADD CONSTRAINT "client_client_addresses_client_id" FOREIGN KEY ("client_id") REFERENCES "client"."client_clients" ("id");

ALTER TABLE "order_orders" ADD CONSTRAINT "order_orders_client_id" FOREIGN KEY ("client_id") REFERENCES "client"."client_clients" ("id");

ALTER TABLE "order_orders" ADD CONSTRAINT "order_orders_delivery_address_id" FOREIGN KEY ("client_id", "delivery_address_id") REFERENCES "client"."client_client_addresses" ("client_id", "id");

ALTER TABLE "order_orders" ADD CONSTRAINT "order_orders_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "analytics"."analytics_promotions" ("id");

ALTER TABLE "order_orders" ADD CONSTRAINT "order_orders_segment_id" FOREIGN KEY ("segment_id") REFERENCES "analytics"."analytics_segments" ("id");

ALTER TABLE "order_orders" ADD CONSTRAINT "order_orders_business_area_id" FOREIGN KEY ("business_area_id") REFERENCES "analytics"."analytics_business_areas" ("id");

ALTER TABLE "order_order_lines" ADD CONSTRAINT "order_order_lines_order_id" FOREIGN KEY ("order_id") REFERENCES "order_orders" ("id");

ALTER TABLE "order_order_lines" ADD CONSTRAINT "order_order_lines_item_id" FOREIGN KEY ("item_id") REFERENCES "order_items" ("id");

ALTER TABLE "order_order_lines" ADD CONSTRAINT "order_order_lines_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "analytics"."analytics_promotions" ("id");

ALTER TABLE "order_order_lines" ADD CONSTRAINT "order_order_lines_segment_id" FOREIGN KEY ("segment_id") REFERENCES "analytics"."analytics_segments" ("id");

ALTER TABLE "order_order_lines" ADD CONSTRAINT "order_order_lines_business_area_id" FOREIGN KEY ("business_area_id") REFERENCES "analytics"."analytics_business_areas" ("id");

