// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.analytics.model



/**
 * Attribute value
 */
data class AttributeValueId(

    /**
     * Attribute id
     */
    var attributeId: String = "",

    /**
     * Attribute value id
     */
    var attributeValueId: String = "",
) : Serializable 