-- Finance model
-- Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).


CREATE TABLE "countries" (
  "id" varchar(3) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "key" varchar(3),
  "language_id" varchar(3) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "languages" (
  "id" varchar(3) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "currencies" (
  "id" varchar(5) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "short_name" varchar(20) NOT NULL,
  "iso_code" varchar(3) NOT NULL,
  "key" varchar(3) NOT NULL,
  "decimals" integer NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "exchange_rate_types" (
  "id" varchar(4) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "exchange_rates" (
  "exchange_rate_type_id" varchar(4) NOT NULL,
  "from_currency_id" varchar(5) NOT NULL,
  "to_currency_id" varchar(5) NOT NULL,
  "effective_from" date NOT NULL,
  "exchange_rate" decimal(25,5) NOT NULL,
  "ratio_from" integer NOT NULL,
  "ratio_to" integer NOT NULL,
  "direct_rate" boolean NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("exchange_rate_type_id", "from_currency_id", "to_currency_id", "effective_from")
);

CREATE TABLE "units_of_measurement" (
  "id" varchar(6) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "short_name" varchar(30) NOT NULL,
  "iso_code" varchar(3),
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "uom_texts" (
  "language_id" varchar(3) NOT NULL,
  "uom_id" varchar(6) NOT NULL,
  "name" varchar(100) NOT NULL,
  "short_name" varchar(20) NOT NULL,
  "commercial_code" varchar(6) NOT NULL,
  "technical_code" varchar(6) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("language_id", "uom_id")
);

CREATE TABLE "company_code"."company_codes" (
  "id" varchar(4) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "country_id" varchar(3) NOT NULL,
  "language_id" varchar(3) NOT NULL,
  "currency_id" varchar(5) NOT NULL,
  "chart_of_accounts_id" varchar(4) NOT NULL,
  "fy_variant_id" varchar(2) NOT NULL,
  "posting_period_variant_id" varchar(4) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "company_code"."company_code_ledgers" (
  "company_code_id" varchar(4) NOT NULL,
  "ledger_id" varchar(4) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("company_code_id", "ledger_id")
);

CREATE TABLE "company_code"."fy_variants" (
  "id" varchar(2) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "company_code"."posting_period_variants" (
  "id" varchar(4) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "company_code"."open_periods" (
  "posting_period_variant_id" varchar(4) NOT NULL,
  "account_type" account_type NOT NULL,
  "to_account" varchar(10) NOT NULL,
  "from_account" varchar(10) NOT NULL,
  "from_fy1" integer NOT NULL,
  "from_period1" integer NOT NULL,
  "to_fy1" integer NOT NULL,
  "to_period1" integer NOT NULL,
  "from_fy2" integer NOT NULL,
  "from_period2" integer NOT NULL,
  "to_fy2" integer NOT NULL,
  "to_period2" integer NOT NULL,
  "from_fy3" integer NOT NULL,
  "from_period3" integer NOT NULL,
  "to_fy3" integer NOT NULL,
  "to_period3" integer NOT NULL,
  PRIMARY KEY ("posting_period_variant_id", "account_type", "to_account")
);

CREATE TABLE "gl_account"."charts_of_accounts" (
  "id" varchar(4) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "gl_account"."gl_accounts" (
  "chart_of_accounts_id" varchar(4) NOT NULL,
  "gl_account_id" varchar(10) NOT NULL,
  "short_name" varchar(20) NOT NULL,
  "name" varchar(100) NOT NULL,
  "gl_account_type" g_l_account_type NOT NULL,
  "gl_account_group_id" varchar(10) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("chart_of_accounts_id", "gl_account_id")
);

CREATE TABLE "gl_account"."gl_account_groups" (
  "chart_of_accounts_id" varchar(4) NOT NULL,
  "gl_account_group_id" varchar(10) NOT NULL,
  "name" varchar(100) NOT NULL,
  "gl_account_id" varchar(10) NOT NULL,
  "from_gl_account_id" varchar(10) NOT NULL,
  "to_gl_account_id" varchar(10) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("chart_of_accounts_id", "gl_account_group_id")
);

CREATE TABLE "ledger"."ledgers" (
  "id" varchar(4) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "leading" boolean NOT NULL,
  "ledger_type" ledger_type NOT NULL,
  "underlying_ledger" varchar(4),
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "ledger"."ledger_groups" (
  "id" varchar(2) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "ledger"."ledger_group_ledgers" (
  "ledger_group_id" varchar(2) NOT NULL,
  "ledger_id" varchar(4) NOT NULL,
  "representative" boolean NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("ledger_group_id", "ledger_id")
);

CREATE TABLE "ledger_entry"."ledger_entries" (
  "entry_no" uuid PRIMARY KEY NOT NULL,
  "ledger_id" varchar(4) NOT NULL,
  "company_code_id" varchar(4) NOT NULL,
  "fiscal_year" integer NOT NULL,
  "document_number" varchar(10) NOT NULL,
  "line_item_no" varchar(6) NOT NULL,
  "posting_date" date NOT NULL,
  "document_date" date NOT NULL,
  "valuation_date" date NOT NULL,
  "period" integer NOT NULL,
  "fy_period" integer NOT NULL,
  "chart_of_accounts_id" varchar(4) NOT NULL,
  "gl_account_id" varchar(10) NOT NULL,
  "creditor_id" varchar(10),
  "debtor_id" varchar(10),
  "business_partner_id" varchar(10),
  "business_area_id" varchar(4),
  "functional_area_id" varchar(20),
  "segment_id" varchar(10),
  "valuation_area_id" varchar(20),
  "plant_id" varchar(4),
  "location_id" varchar(10),
  "material_id" varchar(40),
  "debit_credit" debit_credit NOT NULL,
  "document_amount" decimal(25,2) NOT NULL,
  "document_currency_id" varchar(5) NOT NULL,
  "company_code_amount" decimal(25,2) NOT NULL,
  "company_code_currency_id" varchar(5) NOT NULL,
  "quantity" decimal(25,3),
  "uom_id" varchar(6),
  "basic_uom_id" varchar(6),
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "ledger_entry"."ledger_entry_attributes" (
  "entry_no" uuid NOT NULL,
  "attribute_id" varchar(10) NOT NULL,
  "attribute_value_id" varchar(20) NOT NULL,
  PRIMARY KEY ("entry_no", "attribute_id", "attribute_value_id")
);

CREATE TABLE "bp"."creditors" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "bp"."debtors" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "bp"."business_partners" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "creditor_id" varchar(10),
  "debtor_id" varchar(10),
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."business_areas" (
  "id" varchar(4) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."functional_areas" (
  "id" varchar(20) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."segments" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."attributes" (
  "id" varchar(10) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "analytics"."attribute_values" (
  "attribute_id" varchar(10) NOT NULL,
  "attribute_value_id" varchar(20) NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("attribute_id", "attribute_value_id")
);

CREATE TABLE "analytics"."valuation_areas" (
  "id" varchar(20) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "short_name" varchar(20) NOT NULL,
  "company_code_id" varchar(4) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "logistic"."materials" (
  "id" varchar(40) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "short_name" varchar(20) NOT NULL,
  "basic_uom_id" varchar(6) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "logistic"."plants" (
  "id" varchar(4) PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "short_name" varchar(20) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "logistic"."locations" (
  "plant_id" varchar(4) NOT NULL,
  "location_id" varchar(10) NOT NULL,
  "name" varchar(100) NOT NULL,
  "short_name" varchar(20) NOT NULL,
  "created_by" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_by" varchar(20) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("plant_id", "location_id")
);


CREATE UNIQUE INDEX "ledger_entries_pk" ON "ledger_entry"."ledger_entries" ("ledger_id", "company_code_id", "fiscal_year", "document_number", "line_item_no");

CREATE UNIQUE INDEX "business_partners_creditor_id" ON "bp"."business_partners" ("creditor_id");

CREATE UNIQUE INDEX "business_partners_debtor_id" ON "bp"."business_partners" ("debtor_id");


COMMENT ON TABLE "countries" IS 'Country';

COMMENT ON COLUMN "countries"."id" IS 'Country Id';

COMMENT ON COLUMN "countries"."name" IS 'Name';

COMMENT ON COLUMN "countries"."key" IS 'Country Key';

COMMENT ON COLUMN "countries"."language_id" IS 'Language Id';

COMMENT ON COLUMN "countries"."created_by" IS 'User created record';

COMMENT ON COLUMN "countries"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "countries"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "countries"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "languages" IS 'Language';

COMMENT ON COLUMN "languages"."id" IS 'Language Id';

COMMENT ON COLUMN "languages"."name" IS 'Name';

COMMENT ON COLUMN "languages"."created_by" IS 'User created record';

COMMENT ON COLUMN "languages"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "languages"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "languages"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "currencies" IS 'Currency';

COMMENT ON COLUMN "currencies"."id" IS 'Currency Id';

COMMENT ON COLUMN "currencies"."name" IS 'Name';

COMMENT ON COLUMN "currencies"."short_name" IS 'Short name';

COMMENT ON COLUMN "currencies"."iso_code" IS 'Currency ISO code';

COMMENT ON COLUMN "currencies"."key" IS 'Currency key';

COMMENT ON COLUMN "currencies"."decimals" IS 'Currency decimals';

COMMENT ON COLUMN "currencies"."created_by" IS 'User created record';

COMMENT ON COLUMN "currencies"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "currencies"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "currencies"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "exchange_rate_types" IS 'Exchange rate type';

COMMENT ON COLUMN "exchange_rate_types"."id" IS 'Exchange rate type Id';

COMMENT ON COLUMN "exchange_rate_types"."name" IS 'Name';

COMMENT ON COLUMN "exchange_rate_types"."created_by" IS 'User created record';

COMMENT ON COLUMN "exchange_rate_types"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "exchange_rate_types"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "exchange_rate_types"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "exchange_rates" IS 'ExchangeRate';

COMMENT ON COLUMN "exchange_rates"."exchange_rate_type_id" IS 'Exchange rate type Id';

COMMENT ON COLUMN "exchange_rates"."from_currency_id" IS 'From Currency Id';

COMMENT ON COLUMN "exchange_rates"."to_currency_id" IS 'To Currency Id';

COMMENT ON COLUMN "exchange_rates"."effective_from" IS 'Effective from';

COMMENT ON COLUMN "exchange_rates"."exchange_rate" IS 'Exchange rate';

COMMENT ON COLUMN "exchange_rates"."ratio_from" IS 'Currency ratio from';

COMMENT ON COLUMN "exchange_rates"."ratio_to" IS 'Currency ratio to';

COMMENT ON COLUMN "exchange_rates"."direct_rate" IS 'Direct ratio indicator';

COMMENT ON COLUMN "exchange_rates"."created_by" IS 'User created record';

COMMENT ON COLUMN "exchange_rates"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "exchange_rates"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "exchange_rates"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "units_of_measurement" IS 'Unit of measurement';

COMMENT ON COLUMN "units_of_measurement"."id" IS 'Unit of measurement Id';

COMMENT ON COLUMN "units_of_measurement"."name" IS 'Name';

COMMENT ON COLUMN "units_of_measurement"."short_name" IS 'Short name';

COMMENT ON COLUMN "units_of_measurement"."iso_code" IS 'ISOCode';

COMMENT ON COLUMN "units_of_measurement"."created_by" IS 'User created record';

COMMENT ON COLUMN "units_of_measurement"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "units_of_measurement"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "units_of_measurement"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "uom_texts" IS 'Unit of measurement text';

COMMENT ON COLUMN "uom_texts"."language_id" IS 'Language Id';

COMMENT ON COLUMN "uom_texts"."uom_id" IS 'Unit of measurement Id';

COMMENT ON COLUMN "uom_texts"."name" IS 'Name';

COMMENT ON COLUMN "uom_texts"."short_name" IS 'Short name';

COMMENT ON COLUMN "uom_texts"."commercial_code" IS 'UoM commercial code';

COMMENT ON COLUMN "uom_texts"."technical_code" IS 'UoM technical code';

COMMENT ON COLUMN "uom_texts"."created_by" IS 'User created record';

COMMENT ON COLUMN "uom_texts"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "uom_texts"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "uom_texts"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "company_code"."company_codes" IS 'Company code';

COMMENT ON COLUMN "company_code"."company_codes"."id" IS 'Company code';

COMMENT ON COLUMN "company_code"."company_codes"."name" IS 'Name';

COMMENT ON COLUMN "company_code"."company_codes"."country_id" IS 'Country Id';

COMMENT ON COLUMN "company_code"."company_codes"."language_id" IS 'Language Id';

COMMENT ON COLUMN "company_code"."company_codes"."currency_id" IS 'Currency Id';

COMMENT ON COLUMN "company_code"."company_codes"."chart_of_accounts_id" IS 'Chart of accounts id';

COMMENT ON COLUMN "company_code"."company_codes"."fy_variant_id" IS 'Fiscal year variant id';

COMMENT ON COLUMN "company_code"."company_codes"."posting_period_variant_id" IS 'Posting period variant id';

COMMENT ON COLUMN "company_code"."company_codes"."created_by" IS 'User created record';

COMMENT ON COLUMN "company_code"."company_codes"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "company_code"."company_codes"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "company_code"."company_codes"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "company_code"."company_code_ledgers" IS 'Company code ledger';

COMMENT ON COLUMN "company_code"."company_code_ledgers"."company_code_id" IS 'Company code';

COMMENT ON COLUMN "company_code"."company_code_ledgers"."ledger_id" IS 'Ledger Id';

COMMENT ON COLUMN "company_code"."company_code_ledgers"."created_by" IS 'User created record';

COMMENT ON COLUMN "company_code"."company_code_ledgers"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "company_code"."company_code_ledgers"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "company_code"."company_code_ledgers"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "company_code"."fy_variants" IS 'Fiscal year variant';

COMMENT ON COLUMN "company_code"."fy_variants"."id" IS 'Fiscal year variant id';

COMMENT ON COLUMN "company_code"."fy_variants"."name" IS 'Name';

COMMENT ON COLUMN "company_code"."fy_variants"."created_by" IS 'User created record';

COMMENT ON COLUMN "company_code"."fy_variants"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "company_code"."fy_variants"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "company_code"."fy_variants"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "company_code"."posting_period_variants" IS 'Posting period variant';

COMMENT ON COLUMN "company_code"."posting_period_variants"."id" IS 'Posting period variant id';

COMMENT ON COLUMN "company_code"."posting_period_variants"."name" IS 'Name';

COMMENT ON COLUMN "company_code"."posting_period_variants"."created_by" IS 'User created record';

COMMENT ON COLUMN "company_code"."posting_period_variants"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "company_code"."posting_period_variants"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "company_code"."posting_period_variants"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "company_code"."open_periods" IS 'Open period';

COMMENT ON COLUMN "company_code"."open_periods"."posting_period_variant_id" IS 'Posting period variant id';

COMMENT ON COLUMN "company_code"."open_periods"."account_type" IS 'Account type';

COMMENT ON COLUMN "company_code"."open_periods"."to_account" IS 'To account';

COMMENT ON COLUMN "company_code"."open_periods"."from_account" IS 'From account';

COMMENT ON COLUMN "company_code"."open_periods"."from_fy1" IS 'Group 1: From fiscal year';

COMMENT ON COLUMN "company_code"."open_periods"."from_period1" IS 'Group 1: From period';

COMMENT ON COLUMN "company_code"."open_periods"."to_fy1" IS 'Group 1: To fiscal year';

COMMENT ON COLUMN "company_code"."open_periods"."to_period1" IS 'Group 1: To period';

COMMENT ON COLUMN "company_code"."open_periods"."from_fy2" IS 'Group 2: From fiscal year';

COMMENT ON COLUMN "company_code"."open_periods"."from_period2" IS 'Group 2: From period';

COMMENT ON COLUMN "company_code"."open_periods"."to_fy2" IS 'Group 2: To fiscal year';

COMMENT ON COLUMN "company_code"."open_periods"."to_period2" IS 'Group 2: To period';

COMMENT ON COLUMN "company_code"."open_periods"."from_fy3" IS 'Group 3: From fiscal year';

COMMENT ON COLUMN "company_code"."open_periods"."from_period3" IS 'Group 3: From period';

COMMENT ON COLUMN "company_code"."open_periods"."to_fy3" IS 'Group 3: To fiscal year';

COMMENT ON COLUMN "company_code"."open_periods"."to_period3" IS 'Group 3: To period';

COMMENT ON TABLE "gl_account"."charts_of_accounts" IS 'Chart of accounts';

COMMENT ON COLUMN "gl_account"."charts_of_accounts"."id" IS 'Chart of accounts id';

COMMENT ON COLUMN "gl_account"."charts_of_accounts"."name" IS 'Name';

COMMENT ON COLUMN "gl_account"."charts_of_accounts"."created_by" IS 'User created record';

COMMENT ON COLUMN "gl_account"."charts_of_accounts"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "gl_account"."charts_of_accounts"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "gl_account"."charts_of_accounts"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "gl_account"."gl_accounts" IS 'General ledger account';

COMMENT ON COLUMN "gl_account"."gl_accounts"."chart_of_accounts_id" IS 'Chart of accounts id';

COMMENT ON COLUMN "gl_account"."gl_accounts"."gl_account_id" IS 'General ledger account id';

COMMENT ON COLUMN "gl_account"."gl_accounts"."short_name" IS 'Short name';

COMMENT ON COLUMN "gl_account"."gl_accounts"."name" IS 'Name';

COMMENT ON COLUMN "gl_account"."gl_accounts"."gl_account_type" IS 'General ledger account type';

COMMENT ON COLUMN "gl_account"."gl_accounts"."gl_account_group_id" IS 'General ledger account group id';

COMMENT ON COLUMN "gl_account"."gl_accounts"."created_by" IS 'User created record';

COMMENT ON COLUMN "gl_account"."gl_accounts"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "gl_account"."gl_accounts"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "gl_account"."gl_accounts"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "gl_account"."gl_account_groups" IS 'General ledger account group';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."chart_of_accounts_id" IS 'Chart of accounts id';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."gl_account_group_id" IS 'General ledger account group id';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."name" IS 'Name';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."gl_account_id" IS 'General ledger account id';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."from_gl_account_id" IS 'From GL account';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."to_gl_account_id" IS 'To GL account';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."created_by" IS 'User created record';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "gl_account"."gl_account_groups"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "ledger"."ledgers" IS 'Ledger';

COMMENT ON COLUMN "ledger"."ledgers"."id" IS 'Ledger Id';

COMMENT ON COLUMN "ledger"."ledgers"."name" IS 'Name';

COMMENT ON COLUMN "ledger"."ledgers"."leading" IS 'Leading ledger indicator';

COMMENT ON COLUMN "ledger"."ledgers"."ledger_type" IS 'Ledger Type';

COMMENT ON COLUMN "ledger"."ledgers"."underlying_ledger" IS 'Underlying ledger';

COMMENT ON COLUMN "ledger"."ledgers"."created_by" IS 'User created record';

COMMENT ON COLUMN "ledger"."ledgers"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "ledger"."ledgers"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "ledger"."ledgers"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "ledger"."ledger_groups" IS 'Ledger Group';

COMMENT ON COLUMN "ledger"."ledger_groups"."id" IS 'Ledger Group Id';

COMMENT ON COLUMN "ledger"."ledger_groups"."name" IS 'Name';

COMMENT ON COLUMN "ledger"."ledger_groups"."created_by" IS 'User created record';

COMMENT ON COLUMN "ledger"."ledger_groups"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "ledger"."ledger_groups"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "ledger"."ledger_groups"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "ledger"."ledger_group_ledgers" IS 'Ledger assignments to ledger group';

COMMENT ON COLUMN "ledger"."ledger_group_ledgers"."ledger_group_id" IS 'Ledger Group Id';

COMMENT ON COLUMN "ledger"."ledger_group_ledgers"."ledger_id" IS 'Ledger Id';

COMMENT ON COLUMN "ledger"."ledger_group_ledgers"."representative" IS 'Representative ledger indicator';

COMMENT ON COLUMN "ledger"."ledger_group_ledgers"."created_by" IS 'User created record';

COMMENT ON COLUMN "ledger"."ledger_group_ledgers"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "ledger"."ledger_group_ledgers"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "ledger"."ledger_group_ledgers"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "ledger_entry"."ledger_entries" IS 'Ledger Entry';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."entry_no" IS 'Entry no';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."ledger_id" IS 'Ledger Id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."company_code_id" IS 'Company code';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."fiscal_year" IS 'Fiscal year';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."document_number" IS 'Document number';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."line_item_no" IS 'Line item no';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."posting_date" IS 'Posting date';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."document_date" IS 'Document date';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."valuation_date" IS 'Valuation date';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."period" IS 'Period';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."fy_period" IS 'Fiscal year period';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."chart_of_accounts_id" IS 'Chart of accounts id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."gl_account_id" IS 'General ledger account id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."creditor_id" IS 'Creditor id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."debtor_id" IS 'Debtor id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."business_partner_id" IS 'Business partner id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."business_area_id" IS 'Business area id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."functional_area_id" IS 'Functional area id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."segment_id" IS 'Segment id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."valuation_area_id" IS 'Valuation area id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."plant_id" IS 'Plant id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."location_id" IS 'Location id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."material_id" IS 'Material id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."debit_credit" IS 'Debit/credit indicator';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."document_amount" IS 'Document amount';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."document_currency_id" IS 'Document currency';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."company_code_amount" IS 'Company code amount';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."company_code_currency_id" IS 'Company code currency';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."quantity" IS 'Quantity';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."uom_id" IS 'Unit of measure id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."basic_uom_id" IS 'Basic unit of measure id';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."created_by" IS 'User created record';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "ledger_entry"."ledger_entries"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "ledger_entry"."ledger_entry_attributes" IS 'Ledger entry attribute';

COMMENT ON COLUMN "ledger_entry"."ledger_entry_attributes"."entry_no" IS 'Entry no';

COMMENT ON COLUMN "ledger_entry"."ledger_entry_attributes"."attribute_id" IS 'Attribute id';

COMMENT ON COLUMN "ledger_entry"."ledger_entry_attributes"."attribute_value_id" IS 'Attribute value id';

COMMENT ON TABLE "bp"."creditors" IS 'Creditor';

COMMENT ON COLUMN "bp"."creditors"."id" IS 'Creditor id';

COMMENT ON COLUMN "bp"."creditors"."name" IS 'Name';

COMMENT ON COLUMN "bp"."creditors"."created_by" IS 'User created record';

COMMENT ON COLUMN "bp"."creditors"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "bp"."creditors"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "bp"."creditors"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "bp"."debtors" IS 'Debtor';

COMMENT ON COLUMN "bp"."debtors"."id" IS 'Debtor id';

COMMENT ON COLUMN "bp"."debtors"."name" IS 'Name';

COMMENT ON COLUMN "bp"."debtors"."created_by" IS 'User created record';

COMMENT ON COLUMN "bp"."debtors"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "bp"."debtors"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "bp"."debtors"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "bp"."business_partners" IS 'Business partner';

COMMENT ON COLUMN "bp"."business_partners"."id" IS 'Business partner id';

COMMENT ON COLUMN "bp"."business_partners"."name" IS 'Name';

COMMENT ON COLUMN "bp"."business_partners"."creditor_id" IS 'Creditor id';

COMMENT ON COLUMN "bp"."business_partners"."debtor_id" IS 'Debtor id';

COMMENT ON COLUMN "bp"."business_partners"."created_by" IS 'User created record';

COMMENT ON COLUMN "bp"."business_partners"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "bp"."business_partners"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "bp"."business_partners"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."business_areas" IS 'Business area';

COMMENT ON COLUMN "analytics"."business_areas"."id" IS 'Business area id';

COMMENT ON COLUMN "analytics"."business_areas"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."business_areas"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."business_areas"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."business_areas"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."business_areas"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."functional_areas" IS 'Functional area';

COMMENT ON COLUMN "analytics"."functional_areas"."id" IS 'Functional area id';

COMMENT ON COLUMN "analytics"."functional_areas"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."functional_areas"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."functional_areas"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."functional_areas"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."functional_areas"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."segments" IS 'Segment';

COMMENT ON COLUMN "analytics"."segments"."id" IS 'Segment id';

COMMENT ON COLUMN "analytics"."segments"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."segments"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."segments"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."segments"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."segments"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."attributes" IS 'Attribute';

COMMENT ON COLUMN "analytics"."attributes"."id" IS 'Attribute id';

COMMENT ON COLUMN "analytics"."attributes"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."attributes"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."attributes"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."attributes"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."attributes"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."attribute_values" IS 'Attribute value';

COMMENT ON COLUMN "analytics"."attribute_values"."attribute_id" IS 'Attribute id';

COMMENT ON COLUMN "analytics"."attribute_values"."attribute_value_id" IS 'Attribute value id';

COMMENT ON COLUMN "analytics"."attribute_values"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."attribute_values"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."attribute_values"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."attribute_values"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."attribute_values"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "analytics"."valuation_areas" IS 'Valuation area';

COMMENT ON COLUMN "analytics"."valuation_areas"."id" IS 'Valuation area id';

COMMENT ON COLUMN "analytics"."valuation_areas"."name" IS 'Name';

COMMENT ON COLUMN "analytics"."valuation_areas"."short_name" IS 'Short name';

COMMENT ON COLUMN "analytics"."valuation_areas"."company_code_id" IS 'Company code';

COMMENT ON COLUMN "analytics"."valuation_areas"."created_by" IS 'User created record';

COMMENT ON COLUMN "analytics"."valuation_areas"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "analytics"."valuation_areas"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "analytics"."valuation_areas"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "logistic"."materials" IS 'Material';

COMMENT ON COLUMN "logistic"."materials"."id" IS 'Material id';

COMMENT ON COLUMN "logistic"."materials"."name" IS 'Name';

COMMENT ON COLUMN "logistic"."materials"."short_name" IS 'Short name';

COMMENT ON COLUMN "logistic"."materials"."basic_uom_id" IS 'Unit of measurement Id';

COMMENT ON COLUMN "logistic"."materials"."created_by" IS 'User created record';

COMMENT ON COLUMN "logistic"."materials"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "logistic"."materials"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "logistic"."materials"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "logistic"."plants" IS 'Plant';

COMMENT ON COLUMN "logistic"."plants"."id" IS 'Plant id';

COMMENT ON COLUMN "logistic"."plants"."name" IS 'Name';

COMMENT ON COLUMN "logistic"."plants"."short_name" IS 'Short name';

COMMENT ON COLUMN "logistic"."plants"."created_by" IS 'User created record';

COMMENT ON COLUMN "logistic"."plants"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "logistic"."plants"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "logistic"."plants"."updated_at" IS 'Timestamp of record update';

COMMENT ON TABLE "logistic"."locations" IS 'Location';

COMMENT ON COLUMN "logistic"."locations"."plant_id" IS 'Plant id';

COMMENT ON COLUMN "logistic"."locations"."location_id" IS 'Location id';

COMMENT ON COLUMN "logistic"."locations"."name" IS 'Name';

COMMENT ON COLUMN "logistic"."locations"."short_name" IS 'Short name';

COMMENT ON COLUMN "logistic"."locations"."created_by" IS 'User created record';

COMMENT ON COLUMN "logistic"."locations"."created_at" IS 'Timestamp of record create';

COMMENT ON COLUMN "logistic"."locations"."updated_by" IS 'User updated record';

COMMENT ON COLUMN "logistic"."locations"."updated_at" IS 'Timestamp of record update';



ALTER TABLE "countries" ADD CONSTRAINT "countries_language_id" FOREIGN KEY ("language_id") REFERENCES "languages" ("id");

ALTER TABLE "exchange_rates" ADD CONSTRAINT "exchange_rates_exchange_rate_type_id" FOREIGN KEY ("exchange_rate_type_id") REFERENCES "exchange_rate_types" ("id");

ALTER TABLE "exchange_rates" ADD CONSTRAINT "exchange_rates_from_currency_id" FOREIGN KEY ("from_currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "exchange_rates" ADD CONSTRAINT "exchange_rates_to_currency_id" FOREIGN KEY ("to_currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "uom_texts" ADD CONSTRAINT "uom_texts_language_id" FOREIGN KEY ("language_id") REFERENCES "languages" ("id");

ALTER TABLE "uom_texts" ADD CONSTRAINT "uom_texts_uom_id" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement" ("id");

ALTER TABLE "company_code"."company_codes" ADD CONSTRAINT "company_codes_country_id" FOREIGN KEY ("country_id") REFERENCES "countries" ("id");

ALTER TABLE "company_code"."company_codes" ADD CONSTRAINT "company_codes_language_id" FOREIGN KEY ("language_id") REFERENCES "languages" ("id");

ALTER TABLE "company_code"."company_codes" ADD CONSTRAINT "company_codes_currency_id" FOREIGN KEY ("currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "company_code"."company_codes" ADD CONSTRAINT "company_codes_chart_of_accounts_id" FOREIGN KEY ("chart_of_accounts_id") REFERENCES "gl_account"."charts_of_accounts" ("id");

ALTER TABLE "company_code"."company_codes" ADD CONSTRAINT "company_codes_fy_variant_id" FOREIGN KEY ("fy_variant_id") REFERENCES "company_code"."fy_variants" ("id");

ALTER TABLE "company_code"."company_codes" ADD CONSTRAINT "company_codes_posting_period_variant_id" FOREIGN KEY ("posting_period_variant_id") REFERENCES "company_code"."posting_period_variants" ("id");

ALTER TABLE "company_code"."company_code_ledgers" ADD CONSTRAINT "company_code_ledgers_company_code_id" FOREIGN KEY ("company_code_id") REFERENCES "company_code"."company_codes" ("id");

ALTER TABLE "company_code"."company_code_ledgers" ADD CONSTRAINT "company_code_ledgers_ledger_id" FOREIGN KEY ("ledger_id") REFERENCES "ledger"."ledgers" ("id");

ALTER TABLE "company_code"."open_periods" ADD CONSTRAINT "open_periods_posting_period_variant_id" FOREIGN KEY ("posting_period_variant_id") REFERENCES "company_code"."posting_period_variants" ("id");

ALTER TABLE "gl_account"."gl_accounts" ADD CONSTRAINT "gl_accounts_chart_of_accounts_id" FOREIGN KEY ("chart_of_accounts_id") REFERENCES "gl_account"."charts_of_accounts" ("id");

ALTER TABLE "gl_account"."gl_accounts" ADD CONSTRAINT "gl_accounts_gl_account_group_id" FOREIGN KEY ("chart_of_accounts_id", "gl_account_group_id") REFERENCES "gl_account"."gl_account_groups" ("chart_of_accounts_id", "gl_account_group_id");

ALTER TABLE "gl_account"."gl_account_groups" ADD CONSTRAINT "gl_account_groups_chart_of_accounts_id" FOREIGN KEY ("chart_of_accounts_id") REFERENCES "gl_account"."charts_of_accounts" ("id");

ALTER TABLE "ledger"."ledgers" ADD CONSTRAINT "ledgers_underlying_ledger" FOREIGN KEY ("underlying_ledger") REFERENCES "ledger"."ledgers" ("id");

ALTER TABLE "ledger"."ledger_group_ledgers" ADD CONSTRAINT "ledger_group_ledgers_ledger_id" FOREIGN KEY ("ledger_id") REFERENCES "ledger"."ledgers" ("id");

ALTER TABLE "ledger"."ledger_group_ledgers" ADD CONSTRAINT "ledger_group_ledgers_ledger_group_id" FOREIGN KEY ("ledger_group_id") REFERENCES "ledger"."ledger_groups" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_ledger_id" FOREIGN KEY ("ledger_id") REFERENCES "ledger"."ledgers" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_company_code_id" FOREIGN KEY ("company_code_id") REFERENCES "company_code"."company_codes" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_gl_account_id" FOREIGN KEY ("chart_of_accounts_id", "gl_account_id") REFERENCES "gl_account"."gl_accounts" ("chart_of_accounts_id", "gl_account_id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_creditor_id" FOREIGN KEY ("creditor_id") REFERENCES "bp"."creditors" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_debtor_id" FOREIGN KEY ("debtor_id") REFERENCES "bp"."debtors" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_business_partner_id" FOREIGN KEY ("business_partner_id") REFERENCES "bp"."business_partners" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_business_area_id" FOREIGN KEY ("business_area_id") REFERENCES "analytics"."business_areas" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_functional_area_id" FOREIGN KEY ("functional_area_id") REFERENCES "analytics"."functional_areas" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_segment_id" FOREIGN KEY ("segment_id") REFERENCES "analytics"."segments" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_valuation_area_id" FOREIGN KEY ("valuation_area_id") REFERENCES "analytics"."valuation_areas" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_plant_id" FOREIGN KEY ("plant_id") REFERENCES "logistic"."plants" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_location_id" FOREIGN KEY ("plant_id", "location_id") REFERENCES "logistic"."locations" ("plant_id", "location_id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_material_id" FOREIGN KEY ("material_id") REFERENCES "logistic"."materials" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_document_currency_id" FOREIGN KEY ("document_currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_company_code_currency_id" FOREIGN KEY ("company_code_currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_uom_id" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement" ("id");

ALTER TABLE "ledger_entry"."ledger_entries" ADD CONSTRAINT "ledger_entries_basic_uom_id" FOREIGN KEY ("basic_uom_id") REFERENCES "units_of_measurement" ("id");

ALTER TABLE "ledger_entry"."ledger_entry_attributes" ADD CONSTRAINT "ledger_entry_attributes_entry_no" FOREIGN KEY ("entry_no") REFERENCES "ledger_entry"."ledger_entries" ("entry_no");

ALTER TABLE "ledger_entry"."ledger_entry_attributes" ADD CONSTRAINT "ledger_entry_attributes_attribute_value_id" FOREIGN KEY ("attribute_id", "attribute_value_id") REFERENCES "analytics"."attribute_values" ("attribute_id", "attribute_value_id");

ALTER TABLE "bp"."business_partners" ADD CONSTRAINT "business_partners_creditor_id" FOREIGN KEY ("creditor_id") REFERENCES "bp"."creditors" ("id");

ALTER TABLE "bp"."business_partners" ADD CONSTRAINT "business_partners_debtor_id" FOREIGN KEY ("debtor_id") REFERENCES "bp"."debtors" ("id");

ALTER TABLE "analytics"."attribute_values" ADD CONSTRAINT "attribute_values_attribute_id" FOREIGN KEY ("attribute_id") REFERENCES "analytics"."attributes" ("id");

ALTER TABLE "analytics"."valuation_areas" ADD CONSTRAINT "valuation_areas_company_code_id" FOREIGN KEY ("company_code_id") REFERENCES "company_code"."company_codes" ("id");

ALTER TABLE "logistic"."materials" ADD CONSTRAINT "materials_basic_uom_id" FOREIGN KEY ("basic_uom_id") REFERENCES "units_of_measurement" ("id");

ALTER TABLE "logistic"."locations" ADD CONSTRAINT "locations_plant_id" FOREIGN KEY ("plant_id") REFERENCES "logistic"."plants" ("id");

