// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package finance.data.fi.anl.model



/**
 * Attribute value
 */
data class AttributeValueId(

    /**
     * Attribute id
     */
    var attributeId: String = "",

    /**
     * Attribute value id
     */
    var attributeValueId: String = "",
) : Serializable 