// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.fi.anl.model

import jakarta.persistence.*
import java.time.Instant
import finance.data.fi.le.model.LedgerEntryAttributeEntity


/**
 * Attribute value
 */
@Entity
@Table(name = "attribute_values", schema = "analytics")
@IdClass(AttributeValueId::class)
data class AttributeValueEntity(

    /**
     * Attribute id
     */
    @Id
    @Column(name = "attribute_id", nullable = false, length = 10)
    var attributeId: String,

    /**
     * Attribute value id
     */
    @Id
    @Column(name = "attribute_value_id", nullable = false, length = 20)
    var attributeValueId: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Relation to Attribute
     */
    @ManyToOne
    @JoinColumn(name = "attribute_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var attribute: AttributeEntity? = null,

    /**
     * Reference to AttributeValue
     */
    @OneToMany(mappedBy = "ledgerEntryAttribute")
    var ledgerEntryAttribute: Collection<LedgerEntryAttributeEntity>? = null,
) 