// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package finance.data.fi.cc.model

import jakarta.persistence.*
import java.time.Instant


/**
 * Company code
 */
@Entity
@Table(name = "company_codes", schema = "company_code")
data class CompanyCodeEntity(

    /**
     * Company code
     */
    @Id
    @Column(name = "id", nullable = false, length = 4)
    var id: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * Country Id
     */
    @Column(name = "country_id", nullable = false, length = 3)
    var countryId: String,

    /**
     * Language Id
     */
    @Column(name = "language_id", nullable = false, length = 3)
    var languageId: String,

    /**
     * Currency Id
     */
    @Column(name = "currency_id", nullable = false, length = 5)
    var currencyId: String,

    /**
     * Chart of accounts id
     */
    @Column(name = "chart_of_accounts_id", nullable = false, length = 4)
    var chartOfAccountsId: String,

    /**
     * Fiscal year variant id
     */
    @Column(name = "fy_variant_id", nullable = false, length = 2)
    var fyVariantId: String,

    /**
     * Posting period variant id
     */
    @Column(name = "posting_period_variant_id", nullable = false, length = 4)
    var postingPeriodVariantId: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,
) 