// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package finance.data.fi.cc.model



/**
 * Company code ledger
 */
data class CompanyCodeLedgerId(

    /**
     * Company code
     */
    var companyCodeId: String = "",

    /**
     * Ledger Id
     */
    var ledgerId: String = "",
) : Serializable 