// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package finance.data.fi.cc.model

import jakarta.persistence.*
import java.time.Instant


/**
 * Company code ledger
 */
@Entity
@Table(name = "company_code_ledgers", schema = "company_code")
@IdClass(CompanyCodeLedgerId::class)
data class CompanyCodeLedgerEntity(

    /**
     * Company code
     */
    @Id
    @Column(name = "company_code_id", nullable = false, length = 4)
    var companyCodeId: String,

    /**
     * Ledger Id
     */
    @Id
    @Column(name = "ledger_id", nullable = false, length = 4)
    var ledgerId: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,
) 