// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package finance.data.fi.cc.model



/**
 * Open period
 */
data class OpenPeriodId(

    /**
     * Posting period variant id
     */
    var postingPeriodVariantId: String = "",

    /**
     * Account type
     */
    var accountType: String = "",

    /**
     * To account
     */
    var toAccount: String = "",
) : Serializable 