// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity



// Address data structure
type AddressEntity struct {
    // First address line
    AddressLine1 string `db:"address_line1"`
    // Second address line
    AddressLine2 *string `db:"address_line2"`
    // City
    City string `db:"city"`
    // State
    State string `db:"state"`
    // Country
    Country string `db:"country"`
    // Post code
    Postcode string `db:"postcode"`
}


