// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity



// Analytics data structure
type AnalyticsEntity struct {
    // Promotion Id
    PromotionId *string `db:"promotion_id"`
    // Segment Id
    SegmentId *string `db:"segment_id"`
    // Business Area Id
    BusinessAreaId *string `db:"business_area_id"`
}


