// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "github.com/shopspring/decimal"
  "time"
)


// Order line
type OrderLineEntity struct {
    // OrderLine Id
    Id int `db:"id"`
    // Order Id
    OrderId int `db:"order_id"`
    // Item Id
    ItemId int `db:"item_id"`
    // Promotion Id
    PromotionId *string `db:"promotion_id"`
    // Segment Id
    SegmentId *string `db:"segment_id"`
    // Business Area Id
    BusinessAreaId *string `db:"business_area_id"`
    // Amount
    Price decimal.Decimal `db:"price"`
    // Quantity
    Quantity decimal.Decimal `db:"quantity"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


