// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package finance.data.fi.gls.model



/**
 * Ledger assignments to ledger group
 */
data class LedgerGroupLedgerId(

    /**
     * Ledger Group Id
     */
    var ledgerGroupId: String = "",

    /**
     * Ledger Id
     */
    var ledgerId: String = "",
) : Serializable 