// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:09

package model

import jakarta.persistence.*
import java.time.Instant


/**
 * Group member
 */
@Entity
@Table(name = "group_members")
data class GroupMemberEntity(

    /**
     * Group member id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    var id: Int,

    /**
     * Group Id
     */
    @Column(name = "group_id", nullable = false)
    var groupId: Int,

    /**
     * Person Id
     */
    @Column(name = "person_id", nullable = false)
    var personId: Int,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Relation to groups
     */
    @ManyToOne
    @JoinColumn(name = "group_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var group: GroupEntity? = null,

    /**
     * Relation to persons
     */
    @ManyToOne
    @JoinColumn(name = "person_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var person: PersonEntity? = null,
) 