// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package model

import jakarta.persistence.*
import java.time.Instant


/**
 * Group
 */
@Entity
@Table(name = "groups")
data class GroupEntity(

    /**
     * Group Id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    var id: Int,

    /**
     * Group name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Relation to groups
     */
    @JsonIgnore
    @OneToMany(mappedBy = "groupMember")
    var groupMember: Collection<GroupMemberEntity>? = null,
) 