// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.lo.model



/**
 * Location
 */
data class LocationId(

    /**
     * Plant id
     */
    var plantId: String = "",

    /**
     * Location id
     */
    var locationId: String = "",
) : Serializable 