// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: cl.date

package finance.data.lo.model



/**
 * Location
 */
data class LocationId(

    /**
     * Plant id
     */
    var plantId: String = "",

    /**
     * Location id
     */
    var locationId: String = "",
) : Serializable 