// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)


// Company code
type CompanyCodeEntity struct {
    // Company code
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Country Id
    CountryId string `db:"country_id"`
    // Language Id
    LanguageId string `db:"language_id"`
    // Currency Id
    CurrencyId string `db:"currency_id"`
    // Chart of accounts id
    ChartOfAccountsId string `db:"chart_of_accounts_id"`
    // Fiscal year variant id
    FyVariantId string `db:"fy_variant_id"`
    // Posting period variant id
    PostingPeriodVariantId string `db:"posting_period_variant_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


