// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-18 21:59:59

package entity

import (
  "time"
)

const (
  CompanyCodeTableName = "company_code.company_codes"
  CompanyCodePK = "company_codes_pkey"
  CompanyCodeFKCountryId = "company_codes_country_id"
  CompanyCodeFKLanguageId = "company_codes_language_id"
  CompanyCodeFKCurrencyId = "company_codes_currency_id"
  CompanyCodeFKChartOfAccountsId = "company_codes_chart_of_accounts_id"
  CompanyCodeFKFyVariantId = "company_codes_fy_variant_id"
  CompanyCodeFKPostingPeriodVariantId = "company_codes_posting_period_variant_id"
)


// Company code
type CompanyCodeEntity struct {
    // Company code
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Country Id
    CountryId string `db:"country_id"`
    // Language Id
    LanguageId string `db:"language_id"`
    // Currency Id
    CurrencyId string `db:"currency_id"`
    // Chart of accounts id
    ChartOfAccountsId string `db:"chart_of_accounts_id"`
    // Fiscal year variant id
    FyVariantId string `db:"fy_variant_id"`
    // Posting period variant id
    PostingPeriodVariantId string `db:"posting_period_variant_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


