// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)


// Country
type CountryEntity struct {
    // Country Id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Country Key
    Key *string `db:"key"`
    // Language Id
    LanguageId string `db:"language_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


