// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity



// Ledger entry attribute
type LedgerEntryAttributeEntity struct {
    // Entry no
    EntryNo string `db:"entry_no"`
    // Attribute id
    AttributeId string `db:"attribute_id"`
    // Attribute value id
    AttributeValueId string `db:"attribute_value_id"`
}


