// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)


// Material
type MaterialEntity struct {
    // Material id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Short name
    ShortName string `db:"short_name"`
    // Unit of measurement Id
    BasicUomId string `db:"basic_uom_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


