// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const (
  PostingPeriodVariantTableName = "company_code.posting_period_variants"
  PostingPeriodVariantPK = "posting_period_variants_pkey"
)


// Posting period variant
type PostingPeriodVariantEntity struct {
    // Posting period variant id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


