// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-18 21:59:59

package entity

import (
  "time"
)

const (
  ValuationAreaTableName = "analytics.valuation_areas"
  ValuationAreaPK = "valuation_areas_pkey"
  ValuationAreaFKCompanyCodeId = "valuation_areas_company_code_id"
)


// Valuation area
type ValuationAreaEntity struct {
    // Valuation area id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Short name
    ShortName string `db:"short_name"`
    // Company code
    CompanyCodeId string `db:"company_code_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


