// Ledger Type
enum ledger_type {
  L [note: 'Leading ledger']
  X [note: 'Extension ledger']
}

// General ledger account type
enum g_l_account_type {
  X [note: 'Balance Sheet Account']
  N [note: 'Nonoperating Expense or Income']
  P [note: 'Primary Costs or Revenue']
  S [note: 'Secondary Costs']
  C [note: 'Cash Account']
}

// Account type
enum account_type {
  A [note: 'Assets']
  D [note: 'Customer']
  K [note: 'Vendor']
  M [note: 'Materials']
  S [note: 'General Ledger']
}

// Debit/Credit
enum debit_credit {
  D [note: 'Debit']
  C [note: 'Credit']
}

// Group FI-BP - Business Partners 

table "Creditor" {
  "Creditor id" varchar(10) [pk, not null, note: 'Creditor id']
  "Name" varchar(100) [not null, note: 'Name']
  "User created record" varchar(20) [not null, note: 'User created record']
  "Timestamp of record create" timestamptz [not null, note: 'Timestamp of record create']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Creditor'
}

table "Debtor" {
  "Debtor id" varchar(10) [pk, not null, note: 'Debtor id']
  "Name" varchar(100) [not null, note: 'Name']
  "User created record" varchar(20) [not null, note: 'User created record']
  "Timestamp of record create" timestamptz [not null, note: 'Timestamp of record create']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Debtor'
}

table "Business partner" {
  "Business partner id" varchar(10) [pk, not null, note: 'Business partner id']
  "Name" varchar(100) [not null, note: 'Name']
  "Creditor id" varchar(10) [note: 'Creditor id']
  "Debtor id" varchar(10) [note: 'Debtor id']
  "User created record" varchar(20) [not null, note: 'User created record']
  "Timestamp of record create" timestamptz [not null, note: 'Timestamp of record create']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("Creditor id") [unique, name: 'business_partners_creditor_id', note: 'Unique creditorId']
    ("Debtor id") [unique, name: 'business_partners_debtor_id', note: 'Unique debtorId']
  }

  note: 'Business partner'
}

// Reference to Creditor
Ref business_partners_creditor_id: "Business partner"."Creditor id" - "Creditor"."Creditor id"
// Reference to Debtor
Ref business_partners_debtor_id: "Business partner"."Debtor id" - "Debtor"."Debtor id"



