// Ledger Type
enum ledger_type {
  L [note: 'Leading ledger']
  X [note: 'Extension ledger']
}

// General ledger account type
enum g_l_account_type {
  X [note: 'Balance Sheet Account']
  N [note: 'Nonoperating Expense or Income']
  P [note: 'Primary Costs or Revenue']
  S [note: 'Secondary Costs']
  C [note: 'Cash Account']
}

// Account type
enum account_type {
  A [note: 'Assets']
  D [note: 'Customer']
  K [note: 'Vendor']
  M [note: 'Materials']
  S [note: 'General Ledger']
}

// Debit/Credit
enum debit_credit {
  D [note: 'Debit']
  C [note: 'Credit']
}

// Group GLAccount - General Ledger account settings 

table "Chart of accounts" {
  "Chart of accounts id" varchar(4) [pk, not null, note: 'Chart of accounts id']
  "Name" varchar(100) [not null, note: 'Name']
  "User created record" varchar(20) [not null, note: 'User created record']
  "Timestamp of record create" timestamptz [not null, note: 'Timestamp of record create']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Chart of accounts'
}

table "General ledger account" {
  "Chart of accounts id" varchar(4) [not null, note: 'Chart of accounts id']
  "General ledger account id" varchar(10) [not null, note: 'General ledger account id']
  "Short name" varchar(20) [not null, note: 'Short name']
  "Name" varchar(100) [not null, note: 'Name']
  "General ledger account type" g_l_account_type [not null, note: 'General ledger account type']
  "General ledger account group id" varchar(10) [not null, note: 'General ledger account group id']
  "User created record" varchar(20) [not null, note: 'User created record']
  "Timestamp of record create" timestamptz [not null, note: 'Timestamp of record create']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("Chart of accounts id", "General ledger account id") [pk]
  }

  note: 'General ledger account'
}

// Reference to Chart Of Accounts
Ref gl_accounts_chart_of_accounts_id: "General ledger account"."Chart of accounts id" > "Chart of accounts"."Chart of accounts id"
// Reference to GLAccountGroup
Ref gl_accounts_gl_account_group_id: "General ledger account".("Chart of accounts id", "General ledger account group id") > "General ledger account group".("Chart of accounts id", "General ledger account group id")


table "General ledger account group" {
  "Chart of accounts id" varchar(4) [not null, note: 'Chart of accounts id']
  "General ledger account group id" varchar(10) [not null, note: 'General ledger account group id']
  "Name" varchar(100) [not null, note: 'Name']
  "General ledger account id" varchar(10) [not null, note: 'General ledger account id']
  "From GL account" varchar(10) [not null, note: 'From GL account']
  "To GL account" varchar(10) [not null, note: 'To GL account']
  "User created record" varchar(20) [not null, note: 'User created record']
  "Timestamp of record create" timestamptz [not null, note: 'Timestamp of record create']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("Chart of accounts id", "General ledger account group id") [pk]
  }

  note: 'General ledger account group'
}

// Reference to Chart Of Accounts
Ref gl_account_groups_chart_of_accounts_id: "General ledger account group"."Chart of accounts id" > "Chart of accounts"."Chart of accounts id"



