// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity


const TableNameAddressEntity = "addresses_table"

// Address data structure
type AddressEntity struct {
    // First address line
    AddressLine1 string `gorm:"column:address_line1;not null"`
    // Second address line
    AddressLine2 *string `gorm:"column:address_line2"`
    // City
    City string `gorm:"column:city;not null"`
    // State
    State string `gorm:"column:state;not null"`
    // Country
    Country string `gorm:"column:country;not null"`
    // Post code
    Postcode string `gorm:"column:postcode;not null"`
}


func (*AddressEntity) TableName() string {
	return TableNameAddressEntity
}
