// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity


const TableNameAnalyticsEntity = "analyticses_table"

// Analytics data structure
type AnalyticsEntity struct {
    // Promotion Id
    PromotionId *string `gorm:"column:promotion_id"`
    // Segment Id
    SegmentId *string `gorm:"column:segment_id"`
    // Business Area Id
    BusinessAreaId *string `gorm:"column:business_area_id"`
}


func (*AnalyticsEntity) TableName() string {
	return TableNameAnalyticsEntity
}
