// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "github.com/shopspring/decimal"
  "time"
)

const TableNameOrderLineEntity = "order_order_lines_table"

// Order line
type OrderLineEntity struct {
    // OrderLine Id
    Id int `gorm:"column:id;primaryKey;not null"`
    // Order Id
    OrderId int `gorm:"column:order_id;not null"`
    // Item Id
    ItemId int `gorm:"column:item_id;not null"`
    // Promotion Id
    PromotionId *string `gorm:"column:promotion_id"`
    // Segment Id
    SegmentId *string `gorm:"column:segment_id"`
    // Business Area Id
    BusinessAreaId *string `gorm:"column:business_area_id"`
    // Amount
    Price decimal.Decimal `gorm:"column:price;not null"`
    // Quantity
    Quantity decimal.Decimal `gorm:"column:quantity;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*OrderLineEntity) TableName() string {
	return TableNameOrderLineEntity
}
