// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.company_code.model



/**
 * Company code ledger
 */
data class CompanyCodeLedgerId(

    /**
     * Company code
     */
    var companyCodeId: String = "",

    /**
     * Ledger Id
     */
    var ledgerId: String = "",
) : Serializable 