// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.company_code.model

import jakarta.persistence.*
import java.time.Instant
import finance.data.ledger.model.LedgerEntity


/**
 * Company code ledger
 */
@Entity
@Table(name = "company_code_ledgers", schema = "company_code")
@IdClass(CompanyCodeLedgerId::class)
data class CompanyCodeLedgerEntity(

    /**
     * Company code
     */
    @Id
    @Column(name = "company_code_id", nullable = false, length = 4)
    var companyCodeId: String,

    /**
     * Ledger Id
     */
    @Id
    @Column(name = "ledger_id", nullable = false, length = 4)
    var ledgerId: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Reference to CompanyCode
     */
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "company_code_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var companyCode: CompanyCodeEntity? = null,

    /**
     * Reference to Ledger
     */
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "ledger_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var ledger: LedgerEntity? = null,
) 