// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.company_code.model



/**
 * Open period
 */
data class OpenPeriodId(

    /**
     * Posting period variant id
     */
    var postingPeriodVariantId: String = "",

    /**
     * Account type
     */
    var accountType: String = "",

    /**
     * To account
     */
    var toAccount: String = "",
) : Serializable 