// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package finance.data.fi.le.model

import jakarta.persistence.*
import java.util.UUID


/**
 * Ledger entry attribute
 */
@Entity
@Table(name = "ledger_entry_attributes", schema = "ledger_entry")
@IdClass(LedgerEntryAttributeId::class)
data class LedgerEntryAttributeEntity(

    /**
     * Entry no
     */
    @Id
    @Column(name = "entry_no", nullable = false)
    var entryNo: UUID,

    /**
     * Attribute id
     */
    @Id
    @Column(name = "attribute_id", nullable = false, length = 10)
    var attributeId: String,

    /**
     * Attribute value id
     */
    @Id
    @Column(name = "attribute_value_id", nullable = false, length = 20)
    var attributeValueId: String,
) 