// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package model

import jakarta.persistence.*


/**
 * Address data structure
 */
@Entity
@Table(name = "addresses")
data class AddressEntity(

    /**
     * First address line
     */
    @Column(name = "address_line1", nullable = false, length = 100)
    var addressLine1: String,

    /**
     * Second address line
     */
    @Column(name = "address_line2", length = 100)
    var addressLine2: String? = null,

    /**
     * City
     */
    @Column(name = "city", nullable = false, length = 50)
    var city: String,

    /**
     * State
     */
    @Column(name = "state", nullable = false, length = 50)
    var state: String,

    /**
     * Country
     */
    @Column(name = "country", nullable = false, length = 50)
    var country: String,

    /**
     * Post code
     */
    @Column(name = "postcode", nullable = false, length = 10)
    var postcode: String,
) 