// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:52

package model

import jakarta.persistence.*
import java.time.Instant


/**
 * Client
 */
@Entity
@Table(name = "client_clients_table", schema = "client")
data class ClientEntity(

    /**
     * Client Id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    var id: Int,

    /**
     * Client name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * Description
     */
    @Column(name = "description")
    var description: String? = null,

    /**
     * First address line
     */
    @Column(name = "billing_address_line1", nullable = false, length = 100)
    var billingAddressLine1: String,

    /**
     * Second address line
     */
    @Column(name = "billing_address_line2", length = 100)
    var billingAddressLine2: String? = null,

    /**
     * City
     */
    @Column(name = "billing_city", nullable = false, length = 50)
    var billingCity: String,

    /**
     * State
     */
    @Column(name = "billing_state", nullable = false, length = 50)
    var billingState: String,

    /**
     * Country
     */
    @Column(name = "billing_country", nullable = false, length = 50)
    var billingCountry: String,

    /**
     * Post code
     */
    @Column(name = "billing_postcode", nullable = false, length = 10)
    var billingPostcode: String,

    /**
     * First address line
     */
    @Column(name = "postal_address_line1", nullable = false, length = 100)
    var postalAddressLine1: String,

    /**
     * Second address line
     */
    @Column(name = "postal_address_line2", length = 100)
    var postalAddressLine2: String? = null,

    /**
     * City
     */
    @Column(name = "postal_city", nullable = false, length = 50)
    var postalCity: String,

    /**
     * State
     */
    @Column(name = "postal_state", nullable = false, length = 50)
    var postalState: String,

    /**
     * Country
     */
    @Column(name = "postal_country", nullable = false, length = 50)
    var postalCountry: String,

    /**
     * Post code
     */
    @Column(name = "postal_postcode", nullable = false, length = 10)
    var postalPostcode: String,

    /**
     * Promotion Id
     */
    @Column(name = "promotion_id", length = 10)
    var promotionId: String? = null,

    /**
     * Segment Id
     */
    @Column(name = "segment_id", length = 10)
    var segmentId: String? = null,

    /**
     * Business Area Id
     */
    @Column(name = "business_area_id", length = 10)
    var businessAreaId: String? = null,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 10)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 10)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,
) 