// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.gl_account.model

import jakarta.persistence.*
import java.time.Instant
import finance.data.company_code.model.CompanyCodeEntity


/**
 * Chart of accounts
 */
@Entity
@Table(name = "charts_of_accounts", schema = "gl_account")
data class ChartOfAccountsEntity(

    /**
     * Chart of accounts id
     */
    @Id
    @Column(name = "id", nullable = false, length = 4)
    var id: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Reference to Chart Of Accounts
     */
    @OneToMany(mappedBy = "gLAccount")
    var gLAccount: Collection<GLAccountEntity>? = null,

    /**
     * Reference to Chart Of Accounts
     */
    @OneToMany(mappedBy = "gLAccountGroup")
    var gLAccountGroup: Collection<GLAccountGroupEntity>? = null,

    /**
     * Reference to ChartOfAccounts
     */
    @OneToMany(mappedBy = "companyCode")
    var companyCode: Collection<CompanyCodeEntity>? = null,
) 