// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.gl_account.model

import jakarta.persistence.*
import java.time.Instant


/**
 * General ledger account group
 */
@Entity
@Table(name = "gl_account_groups", schema = "gl_account")
@IdClass(GLAccountGroupId::class)
data class GLAccountGroupEntity(

    /**
     * Chart of accounts id
     */
    @Id
    @Column(name = "chart_of_accounts_id", nullable = false, length = 4)
    var chartOfAccountsId: String,

    /**
     * General ledger account group id
     */
    @Id
    @Column(name = "gl_account_group_id", nullable = false, length = 10)
    var glAccountGroupId: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * General ledger account id
     */
    @Column(name = "gl_account_id", nullable = false, length = 10)
    var glAccountId: String,

    /**
     * From GL account
     */
    @Column(name = "from_gl_account_id", nullable = false, length = 10)
    var fromGLAccountId: String,

    /**
     * To GL account
     */
    @Column(name = "to_gl_account_id", nullable = false, length = 10)
    var toGLAccountId: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Reference to Chart Of Accounts
     */
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "chart_of_accounts_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var chartOfAccounts: ChartOfAccountsEntity? = null,

    /**
     * Reference to GLAccountGroup
     */
    @JsonIgnore
    @OneToMany(mappedBy = "gLAccount")
    var gLAccount: Collection<GLAccountEntity>? = null,
) 