// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.gl_account.model



/**
 * General ledger account group
 */
data class GLAccountGroupId(

    /**
     * Chart of accounts id
     */
    var chartOfAccountsId: String = "",

    /**
     * General ledger account group id
     */
    var glAccountGroupId: String = "",
) : Serializable 