// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity

import (
  "time"
)

const (
  AttributeValueTableName = "analytics.attribute_values"
  AttributeValuePK = "attribute_values_pkey"
  AttributeValueFKAttributeId = "attribute_values_attribute_id"
)


// Attribute value
type AttributeValueEntity struct {
    // Attribute id
    AttributeId string `gorm:"column:attribute_id;primaryKey;not null"`
    // Attribute value id
    AttributeValueId string `gorm:"column:attribute_value_id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*AttributeValueEntity) TableName() string {
	return AttributeValueTableName
}
