// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:43

package entity

import (
  "time"
)

const (
  CompanyCodeLedgerTableName = "company_code.company_code_ledgers"
  CompanyCodeLedgerPK = "company_code_ledgers_pkey"
  CompanyCodeLedgerFKCompanyCodeId = "company_code_ledgers_company_code_id"
  CompanyCodeLedgerFKLedgerId = "company_code_ledgers_ledger_id"
)


// Company code ledger
type CompanyCodeLedgerEntity struct {
    // Company code
    CompanyCodeId string `gorm:"column:company_code_id;primaryKey;not null"`
    // Ledger Id
    LedgerId string `gorm:"column:ledger_id;primaryKey;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*CompanyCodeLedgerEntity) TableName() string {
	return CompanyCodeLedgerTableName
}
