// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:43

package entity

import (
  "time"
)

const (
  GLAccountGroupTableName = "gl_account.gl_account_groups"
  GLAccountGroupPK = "gl_account_groups_pkey"
  GLAccountGroupFKChartOfAccountsId = "gl_account_groups_chart_of_accounts_id"
)


// General ledger account group
type GLAccountGroupEntity struct {
    // Chart of accounts id
    ChartOfAccountsId string `gorm:"column:chart_of_accounts_id;primaryKey;not null"`
    // General ledger account group id
    GlAccountGroupId string `gorm:"column:gl_account_group_id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // General ledger account id
    GlAccountId string `gorm:"column:gl_account_id;not null"`
    // From GL account
    FromGLAccountId string `gorm:"column:from_gl_account_id;not null"`
    // To GL account
    ToGLAccountId string `gorm:"column:to_gl_account_id;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*GLAccountGroupEntity) TableName() string {
	return GLAccountGroupTableName
}
