// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity

import (
  "time"
)

const (
  LedgerGroupLedgerTableName = "ledger.ledger_group_ledgers"
  LedgerGroupLedgerPK = "ledger_group_ledgers_pkey"
  LedgerGroupLedgerFKLedgerId = "ledger_group_ledgers_ledger_id"
  LedgerGroupLedgerFKLedgerGroupId = "ledger_group_ledgers_ledger_group_id"
)


// Ledger assignments to ledger group
type LedgerGroupLedgerEntity struct {
    // Ledger Group Id
    LedgerGroupId string `gorm:"column:ledger_group_id;primaryKey;not null"`
    // Ledger Id
    LedgerId string `gorm:"column:ledger_id;primaryKey;not null"`
    // Representative ledger indicator
    Representative bool `gorm:"column:representative;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*LedgerGroupLedgerEntity) TableName() string {
	return LedgerGroupLedgerTableName
}
