// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity


const (
  LedgerEntryAttributeTableName = "ledger_entry.ledger_entry_attributes"
  LedgerEntryAttributePK = "ledger_entry_attributes_pkey"
  LedgerEntryAttributeFKEntryNo = "ledger_entry_attributes_entry_no"
  LedgerEntryAttributeFKAttributeValueId = "ledger_entry_attributes_attribute_value_id"
)


// Ledger entry attribute
type LedgerEntryAttributeEntity struct {
    // Entry no
    EntryNo string `gorm:"column:entry_no;primaryKey;not null"`
    // Attribute id
    AttributeId string `gorm:"column:attribute_id;primaryKey;not null"`
    // Attribute value id
    AttributeValueId string `gorm:"column:attribute_value_id;primaryKey;not null"`
}


func (*LedgerEntryAttributeEntity) TableName() string {
	return LedgerEntryAttributeTableName
}
