// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:43

package entity

import (
  "time"
)

const (
  MaterialTableName = "logistic.materials"
  MaterialPK = "materials_pkey"
  MaterialFKBasicUomId = "materials_basic_uom_id"
)


// Material
type MaterialEntity struct {
    // Material id
    Id string `gorm:"column:id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // Short name
    ShortName string `gorm:"column:short_name;not null"`
    // Unit of measurement Id
    BasicUomId string `gorm:"column:basic_uom_id;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*MaterialEntity) TableName() string {
	return MaterialTableName
}
