// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:43

package entity

import (
  "time"
)

const (
  PostingPeriodVariantTableName = "company_code.posting_period_variants"
  PostingPeriodVariantPK = "posting_period_variants_pkey"
)


// Posting period variant
type PostingPeriodVariantEntity struct {
    // Posting period variant id
    Id string `gorm:"column:id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*PostingPeriodVariantEntity) TableName() string {
	return PostingPeriodVariantTableName
}
