// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package finance.data.fi.bp.model

import jakarta.persistence.*
import java.time.Instant


/**
 * Business partner
 */
@Entity
@Table(name = "business_partners", schema = "bp")
data class BusinessPartnerEntity(

    /**
     * Business partner id
     */
    @Id
    @Column(name = "id", nullable = false, length = 10)
    var id: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * Creditor id
     */
    @Column(name = "creditor_id", length = 10)
    var creditorId: String? = null,

    /**
     * Debtor id
     */
    @Column(name = "debtor_id", length = 10)
    var debtorId: String? = null,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,
) 