// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.fi.bp.model

import jakarta.persistence.*
import java.time.Instant
import finance.data.fi.le.model.LedgerEntryEntity


/**
 * Creditor
 */
@Entity
@Table(name = "creditors", schema = "bp")
data class CreditorEntity(

    /**
     * Creditor id
     */
    @Id
    @Column(name = "id", nullable = false, length = 10)
    var id: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Reference to Creditor
     */
    @OneToMany(mappedBy = "creditor")
    var ledgerEntry: Collection<LedgerEntryEntity>? = null,

    /**
     * Reference to Creditor
     */
    @OneToOne(mappedBy = "businessPartner")
    var businessPartner: BusinessPartnerEntity? = null,
) 