// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const TableNameAttributeValueEntity = "analytics.attribute_values"

// Attribute value
type AttributeValueEntity struct {
    // Attribute id
    AttributeId string `gorm:"column:attribute_id;primaryKey;not null"`
    // Attribute value id
    AttributeValueId string `gorm:"column:attribute_value_id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*AttributeValueEntity) TableName() string {
	return TableNameAttributeValueEntity
}
