// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const (
  BusinessPartnerTableName = "bp.business_partners"
  BusinessPartnerPK = "business_partners_pkey"
  BusinessPartnerFKCreditorId = "business_partners_creditor_id"
  BusinessPartnerFKDebtorId = "business_partners_debtor_id"
  BusinessPartnerUQCreditor_id = "business_partners_creditor_id"
  BusinessPartnerUQDebtor_id = "business_partners_debtor_id"
)


// Business partner
type BusinessPartnerEntity struct {
    // Business partner id
    Id string `gorm:"column:id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // Creditor id
    CreditorId *string `gorm:"column:creditor_id"`
    // Debtor id
    DebtorId *string `gorm:"column:debtor_id"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*BusinessPartnerEntity) TableName() string {
	return BusinessPartnerTableName
}
