// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const TableNameCurrencyEntity = "currencies"

// Currency
type CurrencyEntity struct {
    // Currency Id
    Id string `gorm:"column:id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // Short name
    ShortName string `gorm:"column:short_name;not null"`
    // Currency ISO code
    IsoCode string `gorm:"column:iso_code;not null"`
    // Currency key
    Key string `gorm:"column:key;not null"`
    // Currency decimals
    Decimals int `gorm:"column:decimals;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*CurrencyEntity) TableName() string {
	return TableNameCurrencyEntity
}
