// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-18 21:59:59

package entity

import (
  "github.com/shopspring/decimal"
  "time"
)

const (
  ExchangeRateTableName = "exchange_rates"
  ExchangeRatePK = "exchange_rates_pkey"
  ExchangeRateFKExchangeRateTypeId = "exchange_rates_exchange_rate_type_id"
  ExchangeRateFKFromCurrencyId = "exchange_rates_from_currency_id"
  ExchangeRateFKToCurrencyId = "exchange_rates_to_currency_id"
)


// ExchangeRate
type ExchangeRateEntity struct {
    // Exchange rate type Id
    ExchangeRateTypeId string `gorm:"column:exchange_rate_type_id;primaryKey;not null"`
    // From Currency Id
    FromCurrencyId string `gorm:"column:from_currency_id;primaryKey;not null"`
    // To Currency Id
    ToCurrencyId string `gorm:"column:to_currency_id;primaryKey;not null"`
    // Effective from
    EffectiveFrom string `gorm:"column:effective_from;primaryKey;not null"`
    // Exchange rate
    ExchangeRate decimal.Decimal `gorm:"column:exchange_rate;not null"`
    // Currency ratio from
    RatioFrom int `gorm:"column:ratio_from;not null"`
    // Currency ratio to
    RatioTo int `gorm:"column:ratio_to;not null"`
    // Direct ratio indicator
    DirectRate bool `gorm:"column:direct_rate;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*ExchangeRateEntity) TableName() string {
	return ExchangeRateTableName
}
