// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "github.com/shopspring/decimal"
  "time"
)

const TableNameExchangeRateEntity = "exchange_rates"

// ExchangeRate
type ExchangeRateEntity struct {
    // Exchange rate type Id
    ExchangeRateTypeId string `gorm:"column:exchange_rate_type_id;primaryKey;not null"`
    // From Currency Id
    FromCurrencyId string `gorm:"column:from_currency_id;primaryKey;not null"`
    // To Currency Id
    ToCurrencyId string `gorm:"column:to_currency_id;primaryKey;not null"`
    // Effective from
    EffectiveFrom string `gorm:"column:effective_from;primaryKey;not null"`
    // Exchange rate
    ExchangeRate decimal.Decimal `gorm:"column:exchange_rate;not null"`
    // Currency ratio from
    RatioFrom int `gorm:"column:ratio_from;not null"`
    // Currency ratio to
    RatioTo int `gorm:"column:ratio_to;not null"`
    // Direct ratio indicator
    DirectRate bool `gorm:"column:direct_rate;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*ExchangeRateEntity) TableName() string {
	return TableNameExchangeRateEntity
}
