// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const (
  ExchangeRateTypeTableName = "exchange_rate_types"
  ExchangeRateTypePK = "exchange_rate_types_pkey"
)


// Exchange rate type
type ExchangeRateTypeEntity struct {
    // Exchange rate type Id
    Id string `gorm:"column:id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*ExchangeRateTypeEntity) TableName() string {
	return ExchangeRateTypeTableName
}
