// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const TableNameLedgerGroupLedgerEntity = "ledger.ledger_group_ledgers"

// Ledger assignments to ledger group
type LedgerGroupLedgerEntity struct {
    // Ledger Group Id
    LedgerGroupId string `gorm:"column:ledger_group_id;primaryKey;not null"`
    // Ledger Id
    LedgerId string `gorm:"column:ledger_id;primaryKey;not null"`
    // Representative ledger indicator
    Representative bool `gorm:"column:representative;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*LedgerGroupLedgerEntity) TableName() string {
	return TableNameLedgerGroupLedgerEntity
}
