// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity


const TableNameLedgerEntryAttributeEntity = "ledger_entry.ledger_entry_attributes"

// Ledger entry attribute
type LedgerEntryAttributeEntity struct {
    // Entry no
    EntryNo string `gorm:"column:entry_no;primaryKey;not null"`
    // Attribute id
    AttributeId string `gorm:"column:attribute_id;primaryKey;not null"`
    // Attribute value id
    AttributeValueId string `gorm:"column:attribute_value_id;primaryKey;not null"`
}


func (*LedgerEntryAttributeEntity) TableName() string {
	return TableNameLedgerEntryAttributeEntity
}
