// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const (
  UnitOfMeasurementTextTableName = "uom_texts"
  UnitOfMeasurementTextPK = "uom_texts_pkey"
  UnitOfMeasurementTextFKLanguageId = "uom_texts_language_id"
  UnitOfMeasurementTextFKUomId = "uom_texts_uom_id"
)


// Unit of measurement text
type UnitOfMeasurementTextEntity struct {
    // Language Id
    LanguageId string `gorm:"column:language_id;primaryKey;not null"`
    // Unit of measurement Id
    UomId string `gorm:"column:uom_id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // Short name
    ShortName string `gorm:"column:short_name;not null"`
    // UoM commercial code
    CommercialCode string `gorm:"column:commercial_code;not null"`
    // UoM technical code
    TechnicalCode string `gorm:"column:technical_code;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*UnitOfMeasurementTextEntity) TableName() string {
	return UnitOfMeasurementTextTableName
}
