// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const (
  ValuationAreaTableName = "analytics.valuation_areas"
  ValuationAreaPK = "valuation_areas_pkey"
  ValuationAreaFKCompanyCodeId = "valuation_areas_company_code_id"
)


// Valuation area
type ValuationAreaEntity struct {
    // Valuation area id
    Id string `gorm:"column:id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // Short name
    ShortName string `gorm:"column:short_name;not null"`
    // Company code
    CompanyCodeId string `gorm:"column:company_code_id;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*ValuationAreaEntity) TableName() string {
	return ValuationAreaTableName
}
