// Order Status
enum order_status {
  P [note: 'Placed']
  D [note: 'Delivered']
  C [note: 'Canceled']
}

// Group Client - Client tables 

table "client"."client_clients_table" {
  "id" integer [pk, not null, increment, note: 'Client Id']
  "name" varchar(100) [not null, note: 'Client name']
  "description" text [note: 'Description']
  "billing_address_line1" varchar(100) [not null, note: 'First address line']
  "billing_address_line2" varchar(100) [note: 'Second address line']
  "billing_city" varchar(50) [not null, note: 'City']
  "billing_state" varchar(50) [not null, note: 'State']
  "billing_country" varchar(50) [not null, note: 'Country']
  "billing_postcode" varchar(10) [not null, note: 'Post code']
  "postal_address_line1" varchar(100) [not null, note: 'First address line']
  "postal_address_line2" varchar(100) [note: 'Second address line']
  "postal_city" varchar(50) [not null, note: 'City']
  "postal_state" varchar(50) [not null, note: 'State']
  "postal_country" varchar(50) [not null, note: 'Country']
  "postal_postcode" varchar(10) [not null, note: 'Post code']
  "promotion_id" varchar(10) [note: 'Promotion Id']
  "segment_id" varchar(10) [note: 'Segment Id']
  "business_area_id" varchar(10) [note: 'Business Area Id']
  "created_by" varchar(10) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(10) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Client'
}

// Reference to Promotion
Ref client_clients_table_promotion_id: "client"."client_clients_table"."promotion_id" > "analytics"."analytics_promotions_table"."id"
// Reference to Segment
Ref client_clients_table_segment_id: "client"."client_clients_table"."segment_id" > "analytics"."analytics_segments_table"."id"
// Reference to BusinessArea
Ref client_clients_table_business_area_id: "client"."client_clients_table"."business_area_id" > "analytics"."analytics_business_areas_table"."id"


table "client"."client_client_addresses_table" {
  "id" integer [pk, not null, increment, note: 'Address Id']
  "name" varchar(100) [not null, note: 'Address name']
  "description" text [note: 'Description']
  "client_id" integer [not null, note: 'Client Id']
  "address_line1" varchar(100) [not null, note: 'First address line']
  "address_line2" varchar(100) [note: 'Second address line']
  "city" varchar(50) [not null, note: 'City']
  "state" varchar(50) [not null, note: 'State']
  "country" varchar(50) [not null, note: 'Country']
  "postcode" varchar(10) [not null, note: 'Post code']
  "created_by" varchar(10) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(10) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("client_id", "id") [unique, name: 'client_client_addresses_table_client_id_id', note: 'Unique clientId & id']
  }

  note: 'Client address'
}

// Reference to client
Ref client_client_addresses_table_client_id: "client"."client_client_addresses_table"."client_id" > "client"."client_clients_table"."id"



// Related entities 

table "analytics"."analytics_promotions_table" {
  "id" varchar(10) [pk, not null, note: 'Promotion Id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(10) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(10) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Promotion'
}

table "analytics"."analytics_segments_table" {
  "id" varchar(10) [pk, not null, note: 'Segment Id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(10) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(10) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Segment'
}

table "analytics"."analytics_business_areas_table" {
  "id" varchar(10) [pk, not null, note: 'Business Area Id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(10) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(10) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Business area'
}

