// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.logistic.model

import jakarta.persistence.*
import java.time.Instant
import finance.data.common.model.UnitOfMeasurementEntity
import finance.data.ledger_entry.model.LedgerEntryEntity


/**
 * Material
 */
@Entity
@Table(name = "materials", schema = "logistic")
data class MaterialEntity(

    /**
     * Material id
     */
    @Id
    @Column(name = "id", nullable = false, length = 40)
    var id: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * Short name
     */
    @Column(name = "short_name", nullable = false, length = 20)
    var shortName: String,

    /**
     * Unit of measurement Id
     */
    @Column(name = "basic_uom_id", nullable = false, length = 6)
    var basicUomId: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Reference to Unit Of Measurement
     */
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "basic_uom_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var unitOfMeasurement: UnitOfMeasurementEntity? = null,

    /**
     * Reference to Material
     */
    @JsonIgnore
    @OneToMany(mappedBy = "material")
    var ledgerEntry: Collection<LedgerEntryEntity>? = null,
) 