// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: cl.date

package finance.data.fi.gla.model



/**
 * General ledger account
 */
data class GLAccountId(

    /**
     * Chart of accounts id
     */
    var chartOfAccountsId: String = "",

    /**
     * General ledger account id
     */
    var glAccountId: String = "",
) : Serializable 