// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-18 21:59:59

package finance.data.fi.gla.model



/**
 * General ledger account group
 */
data class GLAccountGroupId(

    /**
     * Chart of accounts id
     */
    var chartOfAccountsId: String = "",

    /**
     * General ledger account group id
     */
    var glAccountGroupId: String = "",
) : Serializable 