
// Group PersonGroup - Person Group Model 

table "Person" {
  "Person Id" integer [pk, not null, increment, note: 'Person Id']
  "Person first name" varchar(40) [not null, note: 'Person first name']
  "Person last name" varchar(40) [not null, note: 'Person last name']
  "Search index" text [not null, note: 'Search index']
  "Person attributes" jsonb [not null, note: 'Person attributes']
  "Person external Ids" jsonb [not null, note: 'Person external Ids']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("Person last name", "Person first name") [name: 'persons_lastname_firstname', note: 'Search index by lastname and firstname']
  }

  note: 'Person'
}

table "Group" {
  "Group Id" integer [pk, not null, increment, note: 'Group Id']
  "Group name" varchar(100) [not null, note: 'Group name']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Group'
}

table "Group member" {
  "Group member id" integer [pk, not null, increment, note: 'Group member id']
  "Group Id" integer [not null, note: 'Group Id']
  "Person Id" integer [not null, note: 'Person Id']
  "User updated record" varchar(20) [not null, note: 'User updated record']
  "Timestamp of record update" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("Group Id", "Person Id") [unique, name: 'group_members_person_group_ids', note: 'Person id in each group must be unique']
  }

  note: 'Group member'
}

// Relation to groups
Ref group_members_group_id: "Group member"."Group Id" > "Group"."Group Id"
// Relation to persons
Ref group_members_person_id: "Group member"."Person Id" > "Person"."Person Id"



