// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const TableNameGroupMemberEntity = "group_members"

// Group member
type GroupMemberEntity struct {
    // Group member id
    Id int `gorm:"column:id;primaryKey;not null"`
    // Group Id
    GroupId int `gorm:"column:group_id;not null"`
    // Person Id
    PersonId int `gorm:"column:person_id;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*GroupMemberEntity) TableName() string {
	return TableNameGroupMemberEntity
}
