// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)

const TableNameGroupEntity = "groups"

// Group
type GroupEntity struct {
    // Group Id
    Id int `gorm:"column:id;primaryKey;not null"`
    // Group name
    Name string `gorm:"column:name;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*GroupEntity) TableName() string {
	return TableNameGroupEntity
}
