// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-05 17:08:12

package entity

import (
  "time"
)

const (
  GroupTableName = "groups"
  GroupPK = "groups_pkey"
)


// Group
type GroupEntity struct {
    // Group Id
    Id int16 `gorm:"column:id;primaryKey;not null"`
    // Group name
    Name string `gorm:"column:name;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*GroupEntity) TableName() string {
	return GroupTableName
}
