// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:51

package entity

import (
  "time"
)

const (
  GroupMemberTableName = "group_members"
  GroupMemberPK = "group_members_pkey"
  GroupMemberFKGroupId = "group_members_group_id"
  GroupMemberUQPersonGroupIds = "group_members_person_group_ids"
)


// Group member
type GroupMemberEntity struct {
    // Group member id
    Id int `gorm:"column:id;primaryKey;not null"`
    // Group Id
    GroupId int16 `gorm:"column:group_id;not null"`
    // Person Id
    PersonId int `gorm:"column:person_id;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*GroupMemberEntity) TableName() string {
	return GroupMemberTableName
}
