// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-05 17:08:12

package entity

import (
  "time"
)

const (
  PersonTableName = "persons"
  PersonPK = "persons_pkey"
)


// Person
type PersonEntity struct {
    // Person Id
    Id int `gorm:"column:id;primaryKey;not null"`
    // Person first name
    Firstname string `gorm:"column:firstname;not null"`
    // Person last name
    Lastname string `gorm:"column:lastname;not null"`
    // Search index
    Search string `gorm:"column:search;not null"`
    // Person attributes
    // Map string: string
    Attributes map[string]string `gorm:"column:attributes;not null"`
    // Person external Ids
    ExternalIds map[string]int `gorm:"column:external_ids;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*PersonEntity) TableName() string {
	return PersonTableName
}
