// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity

import (
  "time"
)

const (
  AttributeValueTableName = "analytics.attribute_values"
  AttributeValuePK = "attribute_values_pkey"
  AttributeValueFKAttributeId = "attribute_values_attribute_id"
)


// Attribute value
type AttributeValueEntity struct {
    // Attribute id
    AttributeId string `db:"attribute_id"`
    // Attribute value id
    AttributeValueId string `db:"attribute_value_id"`
    // Name
    Name string `db:"name"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


