// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity

import (
  "time"
)

const (
  CountryTableName = "countries"
  CountryPK = "countries_pkey"
  CountryFKLanguageId = "countries_language_id"
)


// Country
type CountryEntity struct {
    // Country Id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Country Key
    Key *string `db:"key"`
    // Language Id
    LanguageId string `db:"language_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


