// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package entity

import (
  "time"
)

const (
  CurrencyTableName = "currencies"
  CurrencyPK = "currencies_pkey"
)


// Currency
type CurrencyEntity struct {
    // Currency Id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Short name
    ShortName string `db:"short_name"`
    // Currency ISO code
    IsoCode string `db:"iso_code"`
    // Currency key
    Key string `db:"key"`
    // Currency decimals
    Decimals int `db:"decimals"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


