// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package entity

import (
  "time"
)

const (
  GLAccountTableName = "gl_account.gl_accounts"
  GLAccountPK = "gl_accounts_pkey"
  GLAccountFKChartOfAccountsId = "gl_accounts_chart_of_accounts_id"
  GLAccountFKGlAccountGroupId = "gl_accounts_gl_account_group_id"
)


// General ledger account
type GLAccountEntity struct {
    // Chart of accounts id
    ChartOfAccountsId string `db:"chart_of_accounts_id"`
    // General ledger account id
    GlAccountId string `db:"gl_account_id"`
    // Short name
    ShortName string `db:"short_name"`
    // Name
    Name string `db:"name"`
    // General ledger account type
    GlAccountType string `db:"gl_account_type"`
    // General ledger account group id
    GlAccountGroupId string `db:"gl_account_group_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


