// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package entity


const (
  LedgerEntryAttributeTableName = "ledger_entry.ledger_entry_attributes"
  LedgerEntryAttributePK = "ledger_entry_attributes_pkey"
  LedgerEntryAttributeFKEntryNo = "ledger_entry_attributes_entry_no"
  LedgerEntryAttributeFKAttributeValueId = "ledger_entry_attributes_attribute_value_id"
)


// Ledger entry attribute
type LedgerEntryAttributeEntity struct {
    // Entry no
    EntryNo string `db:"entry_no"`
    // Attribute id
    AttributeId string `db:"attribute_id"`
    // Attribute value id
    AttributeValueId string `db:"attribute_value_id"`
}


