// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity

import (
  "time"
)

const (
  LedgerGroupLedgerTableName = "ledger.ledger_group_ledgers"
  LedgerGroupLedgerPK = "ledger_group_ledgers_pkey"
  LedgerGroupLedgerFKLedgerId = "ledger_group_ledgers_ledger_id"
  LedgerGroupLedgerFKLedgerGroupId = "ledger_group_ledgers_ledger_group_id"
)


// Ledger assignments to ledger group
type LedgerGroupLedgerEntity struct {
    // Ledger Group Id
    LedgerGroupId string `db:"ledger_group_id"`
    // Ledger Id
    LedgerId string `db:"ledger_id"`
    // Representative ledger indicator
    Representative bool `db:"representative"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


