// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity

import (
  "time"
)

const (
  LocationTableName = "logistic.locations"
  LocationPK = "locations_pkey"
  LocationFKPlantId = "locations_plant_id"
)


// Location
type LocationEntity struct {
    // Plant id
    PlantId string `db:"plant_id"`
    // Location id
    LocationId string `db:"location_id"`
    // Name
    Name string `db:"name"`
    // Short name
    ShortName string `db:"short_name"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


