// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:44

package entity

import (
  "time"
)

const (
  MaterialTableName = "logistic.materials"
  MaterialPK = "materials_pkey"
  MaterialFKBasicUomId = "materials_basic_uom_id"
)


// Material
type MaterialEntity struct {
    // Material id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Short name
    ShortName string `db:"short_name"`
    // Unit of measurement Id
    BasicUomId string `db:"basic_uom_id"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


