// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity


const (
  OpenPeriodTableName = "company_code.open_periods"
  OpenPeriodPK = "open_periods_pkey"
  OpenPeriodFKPostingPeriodVariantId = "open_periods_posting_period_variant_id"
)


// Open period
type OpenPeriodEntity struct {
    // Posting period variant id
    PostingPeriodVariantId string `db:"posting_period_variant_id"`
    // Account type
    AccountType string `db:"account_type"`
    // To account
    ToAccount string `db:"to_account"`
    // From account
    FromAccount string `db:"from_account"`
    // Group 1: From fiscal year
    FromFy1 int `db:"from_fy1"`
    // Group 1: From period
    FromPeriod1 int `db:"from_period1"`
    // Group 1: To fiscal year
    ToFy1 int `db:"to_fy1"`
    // Group 1: To period
    ToPeriod1 int `db:"to_period1"`
    // Group 2: From fiscal year
    FromFy2 int `db:"from_fy2"`
    // Group 2: From period
    FromPeriod2 int `db:"from_period2"`
    // Group 2: To fiscal year
    ToFy2 int `db:"to_fy2"`
    // Group 2: To period
    ToPeriod2 int `db:"to_period2"`
    // Group 3: From fiscal year
    FromFy3 int `db:"from_fy3"`
    // Group 3: From period
    FromPeriod3 int `db:"from_period3"`
    // Group 3: To fiscal year
    ToFy3 int `db:"to_fy3"`
    // Group 3: To period
    ToPeriod3 int `db:"to_period3"`
}


