// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package entity

import (
  "time"
)

const (
  UnitOfMeasurementTableName = "units_of_measurement"
  UnitOfMeasurementPK = "units_of_measurement_pkey"
)


// Unit of measurement
type UnitOfMeasurementEntity struct {
    // Unit of measurement Id
    Id string `db:"id"`
    // Name
    Name string `db:"name"`
    // Short name
    ShortName string `db:"short_name"`
    // ISOCode
    IsoCode *string `db:"iso_code"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


