// Ledger Type
enum ledger_type {
  L [note: 'Leading ledger']
  X [note: 'Extension ledger']
}

// General ledger account type
enum g_l_account_type {
  X [note: 'Balance Sheet Account']
  N [note: 'Nonoperating Expense or Income']
  P [note: 'Primary Costs or Revenue']
  S [note: 'Secondary Costs']
  C [note: 'Cash Account']
}

// Account type
enum account_type {
  A [note: 'Assets']
  D [note: 'Customer']
  K [note: 'Vendor']
  M [note: 'Materials']
  S [note: 'General Ledger']
}

// Debit/Credit
enum debit_credit {
  D [note: 'Debit']
  C [note: 'Credit']
}

// Group CA-CUR - Currency 

table "currencies" {
  "id" varchar(5) [pk, not null, note: 'Currency Id']
  "name" varchar(100) [not null, note: 'Name']
  "short_name" varchar(20) [not null, note: 'Short name']
  "iso_code" varchar(3) [not null, note: 'Currency ISO code']
  "key" varchar(3) [not null, note: 'Currency key']
  "decimals" integer [not null, note: 'Currency decimals']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Currency'
}

table "exchange_rate_types" {
  "id" varchar(4) [pk, not null, note: 'Exchange rate type Id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Exchange rate type'
}

table "exchange_rates" {
  "exchange_rate_type_id" varchar(4) [not null, note: 'Exchange rate type Id']
  "from_currency_id" varchar(5) [not null, note: 'From Currency Id']
  "to_currency_id" varchar(5) [not null, note: 'To Currency Id']
  "effective_from" date [not null, note: 'Effective from']
  "exchange_rate" decimal(25,5) [not null, note: 'Exchange rate']
  "ratio_from" integer [not null, note: 'Currency ratio from']
  "ratio_to" integer [not null, note: 'Currency ratio to']
  "direct_rate" boolean [not null, note: 'Direct ratio indicator']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("exchange_rate_type_id", "from_currency_id", "to_currency_id", "effective_from") [pk]
  }

  note: 'ExchangeRate'
}

// Reference to exchange rate type
Ref exchange_rates_exchange_rate_type_id: "exchange_rates"."exchange_rate_type_id" > "exchange_rate_types"."id"
// Reference (from) to currency
Ref exchange_rates_from_currency_id: "exchange_rates"."from_currency_id" > "currencies"."id"
// Reference (to) to currency
Ref exchange_rates_to_currency_id: "exchange_rates"."to_currency_id" > "currencies"."id"



