// Ledger Type
enum ledger_type {
  L [note: 'Leading ledger']
  X [note: 'Extension ledger']
}

// General ledger account type
enum g_l_account_type {
  X [note: 'Balance Sheet Account']
  N [note: 'Nonoperating Expense or Income']
  P [note: 'Primary Costs or Revenue']
  S [note: 'Secondary Costs']
  C [note: 'Cash Account']
}

// Account type
enum account_type {
  A [note: 'Assets']
  D [note: 'Customer']
  K [note: 'Vendor']
  M [note: 'Materials']
  S [note: 'General Ledger']
}

// Debit/Credit
enum debit_credit {
  D [note: 'Debit']
  C [note: 'Credit']
}

// Group FI-BP - Business Partners 

table "bp"."creditors" {
  "id" varchar(10) [pk, not null, note: 'Creditor id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Creditor'
}

table "bp"."debtors" {
  "id" varchar(10) [pk, not null, note: 'Debtor id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Debtor'
}

table "bp"."business_partners" {
  "id" varchar(10) [pk, not null, note: 'Business partner id']
  "name" varchar(100) [not null, note: 'Name']
  "creditor_id" varchar(10) [note: 'Creditor id']
  "debtor_id" varchar(10) [note: 'Debtor id']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("creditor_id") [unique, name: 'business_partners_creditor_id', note: 'Unique creditorId']
    ("debtor_id") [unique, name: 'business_partners_debtor_id', note: 'Unique debtorId']
  }

  note: 'Business partner'
}

// Reference to Creditor
Ref business_partners_creditor_id: "bp"."business_partners"."creditor_id" - "bp"."creditors"."id"
// Reference to Debtor
Ref business_partners_debtor_id: "bp"."business_partners"."debtor_id" - "bp"."debtors"."id"



