// Ledger Type
enum ledger_type {
  L [note: 'Leading ledger']
  X [note: 'Extension ledger']
}

// General ledger account type
enum g_l_account_type {
  X [note: 'Balance Sheet Account']
  N [note: 'Nonoperating Expense or Income']
  P [note: 'Primary Costs or Revenue']
  S [note: 'Secondary Costs']
  C [note: 'Cash Account']
}

// Account type
enum account_type {
  A [note: 'Assets']
  D [note: 'Customer']
  K [note: 'Vendor']
  M [note: 'Materials']
  S [note: 'General Ledger']
}

// Debit/Credit
enum debit_credit {
  D [note: 'Debit']
  C [note: 'Credit']
}

// Group FI-CC - Company code tables 

table "company_code"."company_codes" {
  "id" varchar(4) [pk, not null, note: 'Company code']
  "name" varchar(100) [not null, note: 'Name']
  "country_id" varchar(3) [not null, note: 'Country Id']
  "language_id" varchar(3) [not null, note: 'Language Id']
  "currency_id" varchar(5) [not null, note: 'Currency Id']
  "chart_of_accounts_id" varchar(4) [not null, note: 'Chart of accounts id']
  "fy_variant_id" varchar(2) [not null, note: 'Fiscal year variant id']
  "posting_period_variant_id" varchar(4) [not null, note: 'Posting period variant id']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Company code'
}

// Reference to Country
Ref company_codes_country_id: "company_code"."company_codes"."country_id" > "countries"."id"
// Reference to Language
Ref company_codes_language_id: "company_code"."company_codes"."language_id" > "languages"."id"
// Reference to Currency
Ref company_codes_currency_id: "company_code"."company_codes"."currency_id" > "currencies"."id"
// Reference to ChartOfAccounts
Ref company_codes_chart_of_accounts_id: "company_code"."company_codes"."chart_of_accounts_id" > "gl_account"."charts_of_accounts"."id"
// Reference to FYVariant
Ref company_codes_fy_variant_id: "company_code"."company_codes"."fy_variant_id" > "company_code"."fy_variants"."id"
// Reference to PostingPeriodVariant
Ref company_codes_posting_period_variant_id: "company_code"."company_codes"."posting_period_variant_id" > "company_code"."posting_period_variants"."id"


table "company_code"."company_code_ledgers" {
  "company_code_id" varchar(4) [not null, note: 'Company code']
  "ledger_id" varchar(4) [not null, note: 'Ledger Id']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("company_code_id", "ledger_id") [pk]
  }

  note: 'Company code ledger'
}

// Reference to CompanyCode
Ref company_code_ledgers_company_code_id: "company_code"."company_code_ledgers"."company_code_id" > "company_code"."company_codes"."id"
// Reference to Ledger
Ref company_code_ledgers_ledger_id: "company_code"."company_code_ledgers"."ledger_id" > "ledger"."ledgers"."id"


table "company_code"."fy_variants" {
  "id" varchar(2) [pk, not null, note: 'Fiscal year variant id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Fiscal year variant'
}

table "company_code"."posting_period_variants" {
  "id" varchar(4) [pk, not null, note: 'Posting period variant id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Posting period variant'
}

table "company_code"."open_periods" {
  "posting_period_variant_id" varchar(4) [not null, note: 'Posting period variant id']
  "account_type" account_type [not null, note: 'Account type']
  "to_account" varchar(10) [not null, note: 'To account']
  "from_account" varchar(10) [not null, note: 'From account']
  "from_fy1" integer [not null, note: 'Group 1: From fiscal year']
  "from_period1" integer [not null, note: 'Group 1: From period']
  "to_fy1" integer [not null, note: 'Group 1: To fiscal year']
  "to_period1" integer [not null, note: 'Group 1: To period']
  "from_fy2" integer [not null, note: 'Group 2: From fiscal year']
  "from_period2" integer [not null, note: 'Group 2: From period']
  "to_fy2" integer [not null, note: 'Group 2: To fiscal year']
  "to_period2" integer [not null, note: 'Group 2: To period']
  "from_fy3" integer [not null, note: 'Group 3: From fiscal year']
  "from_period3" integer [not null, note: 'Group 3: From period']
  "to_fy3" integer [not null, note: 'Group 3: To fiscal year']
  "to_period3" integer [not null, note: 'Group 3: To period']

  indexes {
    ("posting_period_variant_id", "account_type", "to_account") [pk]
  }

  note: 'Open period'
}

// Reference to PostingPeriodVariant
Ref open_periods_posting_period_variant_id: "company_code"."open_periods"."posting_period_variant_id" > "company_code"."posting_period_variants"."id"



// Related entities 

table "countries" {
  "id" varchar(3) [pk, not null, note: 'Country Id']
  "name" varchar(100) [not null, note: 'Name']
  "key" varchar(3) [note: 'Country Key']
  "language_id" varchar(3) [not null, note: 'Language Id']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Country'
}

table "gl_account"."charts_of_accounts" {
  "id" varchar(4) [pk, not null, note: 'Chart of accounts id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Chart of accounts'
}

table "ledger"."ledgers" {
  "id" varchar(4) [pk, not null, note: 'Ledger Id']
  "name" varchar(100) [not null, note: 'Name']
  "leading" boolean [not null, note: 'Leading ledger indicator']
  "ledger_type" ledger_type [not null, note: 'Ledger Type']
  "underlying_ledger" varchar(4) [note: 'Underlying ledger']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Ledger'
}

table "languages" {
  "id" varchar(3) [pk, not null, note: 'Language Id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Language'
}

table "currencies" {
  "id" varchar(5) [pk, not null, note: 'Currency Id']
  "name" varchar(100) [not null, note: 'Name']
  "short_name" varchar(20) [not null, note: 'Short name']
  "iso_code" varchar(3) [not null, note: 'Currency ISO code']
  "key" varchar(3) [not null, note: 'Currency key']
  "decimals" integer [not null, note: 'Currency decimals']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Currency'
}

