// Ledger Type
enum ledger_type {
  L [note: 'Leading ledger']
  X [note: 'Extension ledger']
}

// General ledger account type
enum g_l_account_type {
  X [note: 'Balance Sheet Account']
  N [note: 'Nonoperating Expense or Income']
  P [note: 'Primary Costs or Revenue']
  S [note: 'Secondary Costs']
  C [note: 'Cash Account']
}

// Account type
enum account_type {
  A [note: 'Assets']
  D [note: 'Customer']
  K [note: 'Vendor']
  M [note: 'Materials']
  S [note: 'General Ledger']
}

// Debit/Credit
enum debit_credit {
  D [note: 'Debit']
  C [note: 'Credit']
}

// Group Ledger - Ledger settings 

table "ledger"."ledgers" {
  "id" varchar(4) [pk, not null, note: 'Ledger Id']
  "name" varchar(100) [not null, note: 'Name']
  "leading" boolean [not null, note: 'Leading ledger indicator']
  "ledger_type" ledger_type [not null, note: 'Ledger Type']
  "underlying_ledger" varchar(4) [note: 'Underlying ledger']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Ledger'
}

// Reference to ledger
Ref ledgers_underlying_ledger: "ledger"."ledgers"."underlying_ledger" > "ledger"."ledgers"."id"


table "ledger"."ledger_groups" {
  "id" varchar(2) [pk, not null, note: 'Ledger Group Id']
  "name" varchar(100) [not null, note: 'Name']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  note: 'Ledger Group'
}

table "ledger"."ledger_group_ledgers" {
  "ledger_group_id" varchar(2) [not null, note: 'Ledger Group Id']
  "ledger_id" varchar(4) [not null, note: 'Ledger Id']
  "representative" boolean [not null, note: 'Representative ledger indicator']
  "created_by" varchar(20) [not null, note: 'User created record']
  "created_at" timestamptz [not null, note: 'Timestamp of record create']
  "updated_by" varchar(20) [not null, note: 'User updated record']
  "updated_at" timestamptz [not null, note: 'Timestamp of record update']

  indexes {
    ("ledger_group_id", "ledger_id") [pk]
  }

  note: 'Ledger assignments to ledger group'
}

// Reference to ledger
Ref ledger_group_ledgers_ledger_id: "ledger"."ledger_group_ledgers"."ledger_id" > "ledger"."ledgers"."id"
// Reference to ledger group
Ref ledger_group_ledgers_ledger_group_id: "ledger"."ledger_group_ledgers"."ledger_group_id" > "ledger"."ledger_groups"."id"



