// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:52

package entity

import (
  "github.com/shopspring/decimal"
  "time"
)

const (
  OrderLineTableName = "order_order_lines_table"
  OrderLinePK = "order_order_lines_table_pkey"
  OrderLineFKOrderId = "order_order_lines_table_order_id"
  OrderLineFKItemId = "order_order_lines_table_item_id"
)


// Order line
type OrderLineEntity struct {
    // OrderLine Id
    Id int `db:"id"`
    // Order Id
    OrderId int `db:"order_id"`
    // Item Id
    ItemId int `db:"item_id"`
    // Promotion Id
    PromotionId *string `db:"promotion_id"`
    // Segment Id
    SegmentId *string `db:"segment_id"`
    // Business Area Id
    BusinessAreaId *string `db:"business_area_id"`
    // Amount
    Price decimal.Decimal `db:"price"`
    // Quantity
    Quantity decimal.Decimal `db:"quantity"`
    // User created record
    CreatedBy string `db:"created_by"`
    // Timestamp of record create
    CreatedAt time.Time `db:"created_at"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


