// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)


// Group member
type GroupMemberEntity struct {
    // Group member id
    Id int `db:"id"`
    // Group Id
    GroupId int `db:"group_id"`
    // Person Id
    PersonId int `db:"person_id"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


