// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package entity

import (
  "time"
)


// Person
type PersonEntity struct {
    // Person Id
    Id int `db:"id"`
    // Person first name
    Firstname string `db:"firstname"`
    // Person last name
    Lastname string `db:"lastname"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


