// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:51

package entity

import (
  "time"
)

const (
  PersonTableName = "persons"
  PersonPK = "persons_pkey"
)


// Person
type PersonEntity struct {
    // Person Id
    Id int `db:"id"`
    // Person first name
    Firstname string `db:"firstname"`
    // Person last name
    Lastname string `db:"lastname"`
    // Search index
    Search string `db:"search"`
    // Person attributes
    // Map string: string
    Attributes map[string]string `db:"attributes"`
    // Person external Ids
    ExternalIds map[string]int `db:"external_ids"`
    // User updated record
    UpdatedBy string `db:"updated_by"`
    // Timestamp of record update
    UpdatedAt time.Time `db:"updated_at"`
}


