// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:07

package finance.data.ca.cur.model

import jakarta.persistence.*
import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate


/**
 * ExchangeRate
 */
@Entity
@Table(name = "exchange_rates")
@IdClass(ExchangeRateId::class)
data class ExchangeRateEntity(

    /**
     * Exchange rate type Id
     */
    @Id
    @Column(name = "exchange_rate_type_id", nullable = false, length = 4)
    var exchangeRateTypeId: String,

    /**
     * From Currency Id
     */
    @Id
    @Column(name = "from_currency_id", nullable = false, length = 5)
    var fromCurrencyId: String,

    /**
     * To Currency Id
     */
    @Id
    @Column(name = "to_currency_id", nullable = false, length = 5)
    var toCurrencyId: String,

    /**
     * Effective from
     */
    @Id
    @Column(name = "effective_from", nullable = false)
    var effectiveFrom: LocalDate,

    /**
     * Exchange rate
     */
    @Column(name = "exchange_rate", nullable = false, precision = 25, scale = 5)
    var exchangeRate: BigDecimal,

    /**
     * Currency ratio from
     */
    @Column(name = "ratio_from", nullable = false)
    var ratioFrom: Int,

    /**
     * Currency ratio to
     */
    @Column(name = "ratio_to", nullable = false)
    var ratioTo: Int,

    /**
     * Direct ratio indicator
     */
    @Column(name = "direct_rate", nullable = false)
    var directRate: Boolean,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,
) 