// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:52

package entity

import (
  "time"
)

const (
  ClientTableName = "client.client_clients_table"
  ClientPK = "client_clients_table_pkey"
)


// Client
type ClientEntity struct {
    // Client Id
    Id int `gorm:"column:id;primaryKey;not null"`
    // Client name
    Name string `gorm:"column:name;not null"`
    // Description
    Description *string `gorm:"column:description"`
    // First address line
    BillingAddressLine1 string `gorm:"column:billing_address_line1;not null"`
    // Second address line
    BillingAddressLine2 *string `gorm:"column:billing_address_line2"`
    // City
    BillingCity string `gorm:"column:billing_city;not null"`
    // State
    BillingState string `gorm:"column:billing_state;not null"`
    // Country
    BillingCountry string `gorm:"column:billing_country;not null"`
    // Post code
    BillingPostcode string `gorm:"column:billing_postcode;not null"`
    // First address line
    PostalAddressLine1 string `gorm:"column:postal_address_line1;not null"`
    // Second address line
    PostalAddressLine2 *string `gorm:"column:postal_address_line2"`
    // City
    PostalCity string `gorm:"column:postal_city;not null"`
    // State
    PostalState string `gorm:"column:postal_state;not null"`
    // Country
    PostalCountry string `gorm:"column:postal_country;not null"`
    // Post code
    PostalPostcode string `gorm:"column:postal_postcode;not null"`
    // Promotion Id
    PromotionId *string `gorm:"column:promotion_id"`
    // Segment Id
    SegmentId *string `gorm:"column:segment_id"`
    // Business Area Id
    BusinessAreaId *string `gorm:"column:business_area_id"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*ClientEntity) TableName() string {
	return ClientTableName
}
