// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-09-13 11:22:52

package entity

import (
  "time"
)

const (
  ClientAddressTableName = "client.client_client_addresses_table"
  ClientAddressPK = "client_client_addresses_table_pkey"
  ClientAddressFKClientId = "client_client_addresses_table_client_id"
  ClientAddressUQClientIdId = "client_client_addresses_table_client_id_id"
)


// Client address
type ClientAddressEntity struct {
    // Address Id
    Id int `gorm:"column:id;primaryKey;not null"`
    // Address name
    Name string `gorm:"column:name;not null"`
    // Description
    Description *string `gorm:"column:description"`
    // Client Id
    ClientId int `gorm:"column:client_id;not null"`
    // First address line
    AddressLine1 string `gorm:"column:address_line1;not null"`
    // Second address line
    AddressLine2 *string `gorm:"column:address_line2"`
    // City
    City string `gorm:"column:city;not null"`
    // State
    State string `gorm:"column:state;not null"`
    // Country
    Country string `gorm:"column:country;not null"`
    // Post code
    Postcode string `gorm:"column:postcode;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*ClientAddressEntity) TableName() string {
	return ClientAddressTableName
}
