// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-19 17:06:09

package entity

import (
  "time"
)

const (
  PromotionTableName = "analytics.analytics_promotions_table"
  PromotionPK = "analytics_promotions_table_pkey"
)


// Promotion
type PromotionEntity struct {
    // Promotion Id
    Id string `gorm:"column:id;primaryKey;not null"`
    // Name
    Name string `gorm:"column:name;not null"`
    // User created record
    CreatedBy string `gorm:"column:created_by;not null"`
    // Timestamp of record create
    CreatedAt time.Time `gorm:"column:created_at;not null"`
    // User updated record
    UpdatedBy string `gorm:"column:updated_by;not null"`
    // Timestamp of record update
    UpdatedAt time.Time `gorm:"column:updated_at;not null"`
}


func (*PromotionEntity) TableName() string {
	return PromotionTableName
}
