// Code generated by Data Dictionary Builder (c) Valery Lobachev (https://github.com/valerylobachev/data-dictionary-builder)
// Date: 2024-08-18 21:59:59

package finance.data.ca.cl.model

import jakarta.persistence.*
import java.time.Instant
import finance.data.fi.cc.model.CompanyCodeEntity


/**
 * Country
 */
@Entity
@Table(name = "countries")
data class CountryEntity(

    /**
     * Country Id
     */
    @Id
    @Column(name = "id", nullable = false, length = 3)
    var id: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * Country Key
     */
    @Column(name = "key", length = 3)
    var key: String? = null,

    /**
     * Language Id
     */
    @Column(name = "language_id", nullable = false, length = 3)
    var languageId: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Reference to language
     */
    @ManyToOne
    @JoinColumn(name = "language_id", referencedColumnName = "id", nullable = false, updatable = false, insertable = false)
    var language: LanguageEntity? = null,

    /**
     * Reference to Country
     */
    @OneToMany(mappedBy = "companyCode")
    var companyCode: Collection<CompanyCodeEntity>? = null,
) 