// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.common.model

import java.time.LocalDate


/**
 * ExchangeRate
 */
data class ExchangeRateId(

    /**
     * Exchange rate type Id
     */
    var exchangeRateTypeId: String = "",

    /**
     * From Currency Id
     */
    var fromCurrencyId: String = "",

    /**
     * To Currency Id
     */
    var toCurrencyId: String = "",

    /**
     * Effective from
     */
    var effectiveFrom: LocalDate = LocalDate.now(),
) : Serializable 