// Code generated by Data Dictionary Builder (https://github.com/valerylobachev/data-dictionary-builder).

package finance.data.common.model

import jakarta.persistence.*
import java.time.Instant


/**
 * Exchange rate type
 */
@Entity
@Table(name = "exchange_rate_types", schema = "common")
data class ExchangeRateTypeEntity(

    /**
     * Exchange rate type Id
     */
    @Id
    @Column(name = "id", nullable = false, length = 4)
    var id: String,

    /**
     * Name
     */
    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    /**
     * User created record
     */
    @Column(name = "created_by", nullable = false, length = 20)
    var createdBy: String,

    /**
     * Timestamp of record create
     */
    @Column(name = "created_at", nullable = false)
    var createdAt: Instant,

    /**
     * User updated record
     */
    @Column(name = "updated_by", nullable = false, length = 20)
    var updatedBy: String,

    /**
     * Timestamp of record update
     */
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    /**
     * Reference to exchange rate type
     */
    @OneToMany(mappedBy = "exchangeRate")
    var exchangeRate: Collection<ExchangeRateEntity>? = null,
) 